// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: kakeya/v1/distributed.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "kakeya.v1";

/**
 * CapabilityRole classifies what a node can do with a given model
 * for another node's agent workload.
 */
export enum CapabilityRole {
  UNSPECIFIED = 0,
  /** VERIFIER - The node can run this model as an AR verifier (sink+window KV). */
  VERIFIER = 1,
  /**
   * PROPOSER - The node can serve ProposeBlock with this model (dLM, DFlash,
   * or the model-free n-gram proposer advertised as model_id
   * "ngram").
   */
  PROPOSER = 2,
  /** EMBEDDER - Reserved for future exchanged capabilities (ADR 0009 §4). */
  EMBEDDER = 3,
  TOOL = 4,
  UNRECOGNIZED = -1,
}

export function capabilityRoleFromJSON(object: any): CapabilityRole {
  switch (object) {
    case 0:
    case "CAPABILITY_ROLE_UNSPECIFIED":
      return CapabilityRole.UNSPECIFIED;
    case 1:
    case "CAPABILITY_ROLE_VERIFIER":
      return CapabilityRole.VERIFIER;
    case 2:
    case "CAPABILITY_ROLE_PROPOSER":
      return CapabilityRole.PROPOSER;
    case 3:
    case "CAPABILITY_ROLE_EMBEDDER":
      return CapabilityRole.EMBEDDER;
    case 4:
    case "CAPABILITY_ROLE_TOOL":
      return CapabilityRole.TOOL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CapabilityRole.UNRECOGNIZED;
  }
}

export function capabilityRoleToJSON(object: CapabilityRole): string {
  switch (object) {
    case CapabilityRole.UNSPECIFIED:
      return "CAPABILITY_ROLE_UNSPECIFIED";
    case CapabilityRole.VERIFIER:
      return "CAPABILITY_ROLE_VERIFIER";
    case CapabilityRole.PROPOSER:
      return "CAPABILITY_ROLE_PROPOSER";
    case CapabilityRole.EMBEDDER:
      return "CAPABILITY_ROLE_EMBEDDER";
    case CapabilityRole.TOOL:
      return "CAPABILITY_ROLE_TOOL";
    case CapabilityRole.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ModelCapability is one (model, role) a node offers. */
export interface ModelCapability {
  /**
   * HuggingFace-style id ("Qwen/Qwen3-0.6B",
   * "mlx-community/Qwen3-1.7B-4bit") or the reserved id "ngram" for
   * the model-free prompt-lookup proposer.
   */
  modelId: string;
  role: CapabilityRole;
  /** Quantization label, informational: "bf16", "4bit-mlx", "none". */
  quantization: string;
  /**
   * Measured throughput hint in tokens/second for this (model, role)
   * on this node. 0 = unmeasured. Placement uses this as the primary
   * score; nodes should publish a real measurement when they have
   * one.
   */
  tokensPerSecond: number;
}

/**
 * NodeCapability is one node's capability card. See
 * docs/design/agent-capability-exchange-platform.md §1.
 */
export interface NodeCapability {
  /**
   * Stable fleet-unique identity, operator-assigned ("mini-attic")
   * or generated. Two nodes sharing a node_id is an operator error;
   * last-writer-wins applies regardless.
   */
  nodeId: string;
  /**
   * host:port where this node's gRPC services (RuntimeService,
   * CapabilityService, ProposerService) are reachable by peers.
   */
  grpcAddress: string;
  /** Informational platform label: "mac-m4-24gb", "linux-x86", ... */
  platform: string;
  /** Unified-memory capacity in bytes; placement tiebreak signal. */
  unifiedMemoryBytes: string;
  /**
   * Installed mlx version; empty string when MLX is unavailable on
   * this node (e.g. Linux x86 fleet members).
   */
  mlxVersion: string;
  /** Models this node offers, one entry per (model, role). */
  models: ModelCapability[];
  /**
   * Wall-clock freshness stamp (seconds since the Unix epoch) set by
   * the owning node each time it re-announces. Merge keeps the card
   * with the larger value per node_id. Fleet clocks are assumed
   * NTP-synced; ttl_seconds must be much larger than worst-case
   * clock skew (design doc §2).
   */
  announcedAtUnix: number;
  /**
   * Card lifetime. A card is expired (dropped on merge and snapshot)
   * once now > announced_at_unix + ttl_seconds.
   */
  ttlSeconds: number;
  /**
   * Optional mlx.distributed ring endpoint for bulk-tensor flows
   * (ADR 0009 §4 item 4). Empty when the node is not part of a ring.
   */
  ringAddress: string;
}

export interface ExchangeCapabilitiesRequest {
  /** Every card the caller currently holds, its own included. */
  knownNodes: NodeCapability[];
}

export interface ExchangeCapabilitiesResponse {
  /** The callee's post-merge view of the fleet, its own card included. */
  knownNodes: NodeCapability[];
}

export interface GetNodeCapabilityRequest {
}

export interface GetNodeCapabilityResponse {
  /** The callee's own card only. */
  node?: NodeCapability | undefined;
}

export interface ProposeBlockRequest {
  /**
   * The committed prefix (prompt + accepted tokens), raw token ids in
   * the verifier tokenizer's vocabulary. Same opacity contract as
   * runtime.proto: the server never templates or interprets them.
   */
  committedTokenIds: number[];
  /**
   * Number of draft tokens to return. The response carries exactly
   * this many token_ids or the RPC fails; partial blocks are a
   * malformed-proposer error, mirroring SpeculativeDecoder's refusal
   * to continue on short blocks.
   */
  blockSize: number;
  /**
   * Diffusion denoising steps for dLM proposers. Proposers that do
   * not iterate (DFlash single-pass, n-gram lookup) accept and
   * ignore it, matching the in-process propose_block contract.
   */
  numSteps: number;
  /**
   * Which advertised proposer model to use. Empty string selects the
   * serving node's default proposer.
   */
  modelId: string;
}

export interface ProposeBlockResponse {
  /** Exactly block_size draft token ids. */
  tokenIds: number[];
  /**
   * Accounting mirrored from BlockProposal so the caller's
   * ProposerStats stay meaningful across the wire.
   */
  diffusionSteps: number;
  forwardPasses: number;
  peakActivationBytes: string;
}

function createBaseModelCapability(): ModelCapability {
  return { modelId: "", role: 0, quantization: "", tokensPerSecond: 0 };
}

export const ModelCapability: MessageFns<ModelCapability> = {
  encode(message: ModelCapability, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.role !== 0) {
      writer.uint32(16).int32(message.role);
    }
    if (message.quantization !== "") {
      writer.uint32(26).string(message.quantization);
    }
    if (message.tokensPerSecond !== 0) {
      writer.uint32(33).double(message.tokensPerSecond);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModelCapability {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModelCapability();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.quantization = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.tokensPerSecond = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModelCapability {
    return {
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      role: isSet(object.role) ? capabilityRoleFromJSON(object.role) : 0,
      quantization: isSet(object.quantization) ? globalThis.String(object.quantization) : "",
      tokensPerSecond: isSet(object.tokensPerSecond)
        ? globalThis.Number(object.tokensPerSecond)
        : isSet(object.tokens_per_second)
        ? globalThis.Number(object.tokens_per_second)
        : 0,
    };
  },

  toJSON(message: ModelCapability): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.role !== 0) {
      obj.role = capabilityRoleToJSON(message.role);
    }
    if (message.quantization !== "") {
      obj.quantization = message.quantization;
    }
    if (message.tokensPerSecond !== 0) {
      obj.tokensPerSecond = message.tokensPerSecond;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ModelCapability>, I>>(base?: I): ModelCapability {
    return ModelCapability.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ModelCapability>, I>>(object: I): ModelCapability {
    const message = createBaseModelCapability();
    message.modelId = object.modelId ?? "";
    message.role = object.role ?? 0;
    message.quantization = object.quantization ?? "";
    message.tokensPerSecond = object.tokensPerSecond ?? 0;
    return message;
  },
};

function createBaseNodeCapability(): NodeCapability {
  return {
    nodeId: "",
    grpcAddress: "",
    platform: "",
    unifiedMemoryBytes: "0",
    mlxVersion: "",
    models: [],
    announcedAtUnix: 0,
    ttlSeconds: 0,
    ringAddress: "",
  };
}

export const NodeCapability: MessageFns<NodeCapability> = {
  encode(message: NodeCapability, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== "") {
      writer.uint32(10).string(message.nodeId);
    }
    if (message.grpcAddress !== "") {
      writer.uint32(18).string(message.grpcAddress);
    }
    if (message.platform !== "") {
      writer.uint32(26).string(message.platform);
    }
    if (message.unifiedMemoryBytes !== "0") {
      writer.uint32(32).uint64(message.unifiedMemoryBytes);
    }
    if (message.mlxVersion !== "") {
      writer.uint32(42).string(message.mlxVersion);
    }
    for (const v of message.models) {
      ModelCapability.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.announcedAtUnix !== 0) {
      writer.uint32(57).double(message.announcedAtUnix);
    }
    if (message.ttlSeconds !== 0) {
      writer.uint32(65).double(message.ttlSeconds);
    }
    if (message.ringAddress !== "") {
      writer.uint32(74).string(message.ringAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NodeCapability {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeCapability();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.grpcAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.unifiedMemoryBytes = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.mlxVersion = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.models.push(ModelCapability.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.announcedAtUnix = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.ttlSeconds = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.ringAddress = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeCapability {
    return {
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
      grpcAddress: isSet(object.grpcAddress)
        ? globalThis.String(object.grpcAddress)
        : isSet(object.grpc_address)
        ? globalThis.String(object.grpc_address)
        : "",
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      unifiedMemoryBytes: isSet(object.unifiedMemoryBytes)
        ? globalThis.String(object.unifiedMemoryBytes)
        : isSet(object.unified_memory_bytes)
        ? globalThis.String(object.unified_memory_bytes)
        : "0",
      mlxVersion: isSet(object.mlxVersion)
        ? globalThis.String(object.mlxVersion)
        : isSet(object.mlx_version)
        ? globalThis.String(object.mlx_version)
        : "",
      models: globalThis.Array.isArray(object?.models)
        ? object.models.map((e: any) => ModelCapability.fromJSON(e))
        : [],
      announcedAtUnix: isSet(object.announcedAtUnix)
        ? globalThis.Number(object.announcedAtUnix)
        : isSet(object.announced_at_unix)
        ? globalThis.Number(object.announced_at_unix)
        : 0,
      ttlSeconds: isSet(object.ttlSeconds)
        ? globalThis.Number(object.ttlSeconds)
        : isSet(object.ttl_seconds)
        ? globalThis.Number(object.ttl_seconds)
        : 0,
      ringAddress: isSet(object.ringAddress)
        ? globalThis.String(object.ringAddress)
        : isSet(object.ring_address)
        ? globalThis.String(object.ring_address)
        : "",
    };
  },

  toJSON(message: NodeCapability): unknown {
    const obj: any = {};
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    if (message.grpcAddress !== "") {
      obj.grpcAddress = message.grpcAddress;
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.unifiedMemoryBytes !== "0") {
      obj.unifiedMemoryBytes = message.unifiedMemoryBytes;
    }
    if (message.mlxVersion !== "") {
      obj.mlxVersion = message.mlxVersion;
    }
    if (message.models?.length) {
      obj.models = message.models.map((e) => ModelCapability.toJSON(e));
    }
    if (message.announcedAtUnix !== 0) {
      obj.announcedAtUnix = message.announcedAtUnix;
    }
    if (message.ttlSeconds !== 0) {
      obj.ttlSeconds = message.ttlSeconds;
    }
    if (message.ringAddress !== "") {
      obj.ringAddress = message.ringAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeCapability>, I>>(base?: I): NodeCapability {
    return NodeCapability.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeCapability>, I>>(object: I): NodeCapability {
    const message = createBaseNodeCapability();
    message.nodeId = object.nodeId ?? "";
    message.grpcAddress = object.grpcAddress ?? "";
    message.platform = object.platform ?? "";
    message.unifiedMemoryBytes = object.unifiedMemoryBytes ?? "0";
    message.mlxVersion = object.mlxVersion ?? "";
    message.models = object.models?.map((e) => ModelCapability.fromPartial(e)) || [];
    message.announcedAtUnix = object.announcedAtUnix ?? 0;
    message.ttlSeconds = object.ttlSeconds ?? 0;
    message.ringAddress = object.ringAddress ?? "";
    return message;
  },
};

function createBaseExchangeCapabilitiesRequest(): ExchangeCapabilitiesRequest {
  return { knownNodes: [] };
}

export const ExchangeCapabilitiesRequest: MessageFns<ExchangeCapabilitiesRequest> = {
  encode(message: ExchangeCapabilitiesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.knownNodes) {
      NodeCapability.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeCapabilitiesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeCapabilitiesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.knownNodes.push(NodeCapability.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeCapabilitiesRequest {
    return {
      knownNodes: globalThis.Array.isArray(object?.knownNodes)
        ? object.knownNodes.map((e: any) => NodeCapability.fromJSON(e))
        : globalThis.Array.isArray(object?.known_nodes)
        ? object.known_nodes.map((e: any) => NodeCapability.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ExchangeCapabilitiesRequest): unknown {
    const obj: any = {};
    if (message.knownNodes?.length) {
      obj.knownNodes = message.knownNodes.map((e) => NodeCapability.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExchangeCapabilitiesRequest>, I>>(base?: I): ExchangeCapabilitiesRequest {
    return ExchangeCapabilitiesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExchangeCapabilitiesRequest>, I>>(object: I): ExchangeCapabilitiesRequest {
    const message = createBaseExchangeCapabilitiesRequest();
    message.knownNodes = object.knownNodes?.map((e) => NodeCapability.fromPartial(e)) || [];
    return message;
  },
};

function createBaseExchangeCapabilitiesResponse(): ExchangeCapabilitiesResponse {
  return { knownNodes: [] };
}

export const ExchangeCapabilitiesResponse: MessageFns<ExchangeCapabilitiesResponse> = {
  encode(message: ExchangeCapabilitiesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.knownNodes) {
      NodeCapability.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeCapabilitiesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeCapabilitiesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.knownNodes.push(NodeCapability.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeCapabilitiesResponse {
    return {
      knownNodes: globalThis.Array.isArray(object?.knownNodes)
        ? object.knownNodes.map((e: any) => NodeCapability.fromJSON(e))
        : globalThis.Array.isArray(object?.known_nodes)
        ? object.known_nodes.map((e: any) => NodeCapability.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ExchangeCapabilitiesResponse): unknown {
    const obj: any = {};
    if (message.knownNodes?.length) {
      obj.knownNodes = message.knownNodes.map((e) => NodeCapability.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExchangeCapabilitiesResponse>, I>>(base?: I): ExchangeCapabilitiesResponse {
    return ExchangeCapabilitiesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExchangeCapabilitiesResponse>, I>>(object: I): ExchangeCapabilitiesResponse {
    const message = createBaseExchangeCapabilitiesResponse();
    message.knownNodes = object.knownNodes?.map((e) => NodeCapability.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetNodeCapabilityRequest(): GetNodeCapabilityRequest {
  return {};
}

export const GetNodeCapabilityRequest: MessageFns<GetNodeCapabilityRequest> = {
  encode(_: GetNodeCapabilityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetNodeCapabilityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetNodeCapabilityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetNodeCapabilityRequest {
    return {};
  },

  toJSON(_: GetNodeCapabilityRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetNodeCapabilityRequest>, I>>(base?: I): GetNodeCapabilityRequest {
    return GetNodeCapabilityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetNodeCapabilityRequest>, I>>(_: I): GetNodeCapabilityRequest {
    const message = createBaseGetNodeCapabilityRequest();
    return message;
  },
};

function createBaseGetNodeCapabilityResponse(): GetNodeCapabilityResponse {
  return { node: undefined };
}

export const GetNodeCapabilityResponse: MessageFns<GetNodeCapabilityResponse> = {
  encode(message: GetNodeCapabilityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.node !== undefined) {
      NodeCapability.encode(message.node, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetNodeCapabilityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetNodeCapabilityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.node = NodeCapability.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetNodeCapabilityResponse {
    return { node: isSet(object.node) ? NodeCapability.fromJSON(object.node) : undefined };
  },

  toJSON(message: GetNodeCapabilityResponse): unknown {
    const obj: any = {};
    if (message.node !== undefined) {
      obj.node = NodeCapability.toJSON(message.node);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetNodeCapabilityResponse>, I>>(base?: I): GetNodeCapabilityResponse {
    return GetNodeCapabilityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetNodeCapabilityResponse>, I>>(object: I): GetNodeCapabilityResponse {
    const message = createBaseGetNodeCapabilityResponse();
    message.node = (object.node !== undefined && object.node !== null)
      ? NodeCapability.fromPartial(object.node)
      : undefined;
    return message;
  },
};

function createBaseProposeBlockRequest(): ProposeBlockRequest {
  return { committedTokenIds: [], blockSize: 0, numSteps: 0, modelId: "" };
}

export const ProposeBlockRequest: MessageFns<ProposeBlockRequest> = {
  encode(message: ProposeBlockRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.committedTokenIds) {
      writer.uint32(v);
    }
    writer.join();
    if (message.blockSize !== 0) {
      writer.uint32(16).uint32(message.blockSize);
    }
    if (message.numSteps !== 0) {
      writer.uint32(24).uint32(message.numSteps);
    }
    if (message.modelId !== "") {
      writer.uint32(34).string(message.modelId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProposeBlockRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProposeBlockRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.committedTokenIds.push(reader.uint32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.committedTokenIds.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.blockSize = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.numSteps = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProposeBlockRequest {
    return {
      committedTokenIds: globalThis.Array.isArray(object?.committedTokenIds)
        ? object.committedTokenIds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.committed_token_ids)
        ? object.committed_token_ids.map((e: any) => globalThis.Number(e))
        : [],
      blockSize: isSet(object.blockSize)
        ? globalThis.Number(object.blockSize)
        : isSet(object.block_size)
        ? globalThis.Number(object.block_size)
        : 0,
      numSteps: isSet(object.numSteps)
        ? globalThis.Number(object.numSteps)
        : isSet(object.num_steps)
        ? globalThis.Number(object.num_steps)
        : 0,
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
    };
  },

  toJSON(message: ProposeBlockRequest): unknown {
    const obj: any = {};
    if (message.committedTokenIds?.length) {
      obj.committedTokenIds = message.committedTokenIds.map((e) => Math.round(e));
    }
    if (message.blockSize !== 0) {
      obj.blockSize = Math.round(message.blockSize);
    }
    if (message.numSteps !== 0) {
      obj.numSteps = Math.round(message.numSteps);
    }
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProposeBlockRequest>, I>>(base?: I): ProposeBlockRequest {
    return ProposeBlockRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProposeBlockRequest>, I>>(object: I): ProposeBlockRequest {
    const message = createBaseProposeBlockRequest();
    message.committedTokenIds = object.committedTokenIds?.map((e) => e) || [];
    message.blockSize = object.blockSize ?? 0;
    message.numSteps = object.numSteps ?? 0;
    message.modelId = object.modelId ?? "";
    return message;
  },
};

function createBaseProposeBlockResponse(): ProposeBlockResponse {
  return { tokenIds: [], diffusionSteps: 0, forwardPasses: 0, peakActivationBytes: "0" };
}

export const ProposeBlockResponse: MessageFns<ProposeBlockResponse> = {
  encode(message: ProposeBlockResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.tokenIds) {
      writer.uint32(v);
    }
    writer.join();
    if (message.diffusionSteps !== 0) {
      writer.uint32(16).uint32(message.diffusionSteps);
    }
    if (message.forwardPasses !== 0) {
      writer.uint32(24).uint32(message.forwardPasses);
    }
    if (message.peakActivationBytes !== "0") {
      writer.uint32(32).uint64(message.peakActivationBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProposeBlockResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProposeBlockResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.tokenIds.push(reader.uint32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.tokenIds.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.diffusionSteps = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.forwardPasses = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.peakActivationBytes = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProposeBlockResponse {
    return {
      tokenIds: globalThis.Array.isArray(object?.tokenIds)
        ? object.tokenIds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.token_ids)
        ? object.token_ids.map((e: any) => globalThis.Number(e))
        : [],
      diffusionSteps: isSet(object.diffusionSteps)
        ? globalThis.Number(object.diffusionSteps)
        : isSet(object.diffusion_steps)
        ? globalThis.Number(object.diffusion_steps)
        : 0,
      forwardPasses: isSet(object.forwardPasses)
        ? globalThis.Number(object.forwardPasses)
        : isSet(object.forward_passes)
        ? globalThis.Number(object.forward_passes)
        : 0,
      peakActivationBytes: isSet(object.peakActivationBytes)
        ? globalThis.String(object.peakActivationBytes)
        : isSet(object.peak_activation_bytes)
        ? globalThis.String(object.peak_activation_bytes)
        : "0",
    };
  },

  toJSON(message: ProposeBlockResponse): unknown {
    const obj: any = {};
    if (message.tokenIds?.length) {
      obj.tokenIds = message.tokenIds.map((e) => Math.round(e));
    }
    if (message.diffusionSteps !== 0) {
      obj.diffusionSteps = Math.round(message.diffusionSteps);
    }
    if (message.forwardPasses !== 0) {
      obj.forwardPasses = Math.round(message.forwardPasses);
    }
    if (message.peakActivationBytes !== "0") {
      obj.peakActivationBytes = message.peakActivationBytes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProposeBlockResponse>, I>>(base?: I): ProposeBlockResponse {
    return ProposeBlockResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProposeBlockResponse>, I>>(object: I): ProposeBlockResponse {
    const message = createBaseProposeBlockResponse();
    message.tokenIds = object.tokenIds?.map((e) => e) || [];
    message.diffusionSteps = object.diffusionSteps ?? 0;
    message.forwardPasses = object.forwardPasses ?? 0;
    message.peakActivationBytes = object.peakActivationBytes ?? "0";
    return message;
  },
};

/**
 * CapabilityService is served by every Kakeya node that participates
 * in a fleet. Both RPCs are safe to call from any peer at any time;
 * neither mutates anything beyond the callee's capability registry.
 */
export type CapabilityServiceService = typeof CapabilityServiceService;
export const CapabilityServiceService = {
  /**
   * ExchangeCapabilities is the gossip primitive. The caller sends
   * every capability card it currently holds (its own card included);
   * the callee merges those cards into its registry (last-writer-wins
   * on announced_at_unix, own card never overwritten) and replies
   * with its merged view. The caller merges the response. After one
   * round both sides hold the union of their prior views.
   */
  exchangeCapabilities: {
    path: "/kakeya.v1.CapabilityService/ExchangeCapabilities" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ExchangeCapabilitiesRequest): Buffer =>
      Buffer.from(ExchangeCapabilitiesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ExchangeCapabilitiesRequest => ExchangeCapabilitiesRequest.decode(value),
    responseSerialize: (value: ExchangeCapabilitiesResponse): Buffer =>
      Buffer.from(ExchangeCapabilitiesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ExchangeCapabilitiesResponse => ExchangeCapabilitiesResponse.decode(value),
  },
  /**
   * GetNodeCapability returns only the callee's own card. Cheap
   * probe used for liveness checks and diagnostics; does not mutate
   * the callee's registry.
   */
  getNodeCapability: {
    path: "/kakeya.v1.CapabilityService/GetNodeCapability" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetNodeCapabilityRequest): Buffer =>
      Buffer.from(GetNodeCapabilityRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetNodeCapabilityRequest => GetNodeCapabilityRequest.decode(value),
    responseSerialize: (value: GetNodeCapabilityResponse): Buffer =>
      Buffer.from(GetNodeCapabilityResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetNodeCapabilityResponse => GetNodeCapabilityResponse.decode(value),
  },
} as const;

export interface CapabilityServiceServer extends UntypedServiceImplementation {
  /**
   * ExchangeCapabilities is the gossip primitive. The caller sends
   * every capability card it currently holds (its own card included);
   * the callee merges those cards into its registry (last-writer-wins
   * on announced_at_unix, own card never overwritten) and replies
   * with its merged view. The caller merges the response. After one
   * round both sides hold the union of their prior views.
   */
  exchangeCapabilities: handleUnaryCall<ExchangeCapabilitiesRequest, ExchangeCapabilitiesResponse>;
  /**
   * GetNodeCapability returns only the callee's own card. Cheap
   * probe used for liveness checks and diagnostics; does not mutate
   * the callee's registry.
   */
  getNodeCapability: handleUnaryCall<GetNodeCapabilityRequest, GetNodeCapabilityResponse>;
}

export interface CapabilityServiceClient extends Client {
  /**
   * ExchangeCapabilities is the gossip primitive. The caller sends
   * every capability card it currently holds (its own card included);
   * the callee merges those cards into its registry (last-writer-wins
   * on announced_at_unix, own card never overwritten) and replies
   * with its merged view. The caller merges the response. After one
   * round both sides hold the union of their prior views.
   */
  exchangeCapabilities(
    request: ExchangeCapabilitiesRequest,
    callback: (error: ServiceError | null, response: ExchangeCapabilitiesResponse) => void,
  ): ClientUnaryCall;
  exchangeCapabilities(
    request: ExchangeCapabilitiesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ExchangeCapabilitiesResponse) => void,
  ): ClientUnaryCall;
  exchangeCapabilities(
    request: ExchangeCapabilitiesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ExchangeCapabilitiesResponse) => void,
  ): ClientUnaryCall;
  /**
   * GetNodeCapability returns only the callee's own card. Cheap
   * probe used for liveness checks and diagnostics; does not mutate
   * the callee's registry.
   */
  getNodeCapability(
    request: GetNodeCapabilityRequest,
    callback: (error: ServiceError | null, response: GetNodeCapabilityResponse) => void,
  ): ClientUnaryCall;
  getNodeCapability(
    request: GetNodeCapabilityRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetNodeCapabilityResponse) => void,
  ): ClientUnaryCall;
  getNodeCapability(
    request: GetNodeCapabilityRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetNodeCapabilityResponse) => void,
  ): ClientUnaryCall;
}

export const CapabilityServiceClient = makeGenericClientConstructor(
  CapabilityServiceService,
  "kakeya.v1.CapabilityService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): CapabilityServiceClient;
  service: typeof CapabilityServiceService;
  serviceName: string;
};

/**
 * ProposerService serves speculative-decoding draft blocks. The
 * contract is DLMProposer.propose_block (ADR 0001) lifted onto the
 * wire: committed prefix in, exactly block_size draft token ids out.
 */
export type ProposerServiceService = typeof ProposerServiceService;
export const ProposerServiceService = {
  /**
   * ProposeBlock drafts exactly block_size tokens conditioned on the
   * committed prefix. Unknown model_id returns NOT_FOUND; malformed
   * arguments (empty prefix, non-positive block_size/num_steps)
   * return INVALID_ARGUMENT.
   */
  proposeBlock: {
    path: "/kakeya.v1.ProposerService/ProposeBlock" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ProposeBlockRequest): Buffer => Buffer.from(ProposeBlockRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ProposeBlockRequest => ProposeBlockRequest.decode(value),
    responseSerialize: (value: ProposeBlockResponse): Buffer =>
      Buffer.from(ProposeBlockResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ProposeBlockResponse => ProposeBlockResponse.decode(value),
  },
} as const;

export interface ProposerServiceServer extends UntypedServiceImplementation {
  /**
   * ProposeBlock drafts exactly block_size tokens conditioned on the
   * committed prefix. Unknown model_id returns NOT_FOUND; malformed
   * arguments (empty prefix, non-positive block_size/num_steps)
   * return INVALID_ARGUMENT.
   */
  proposeBlock: handleUnaryCall<ProposeBlockRequest, ProposeBlockResponse>;
}

export interface ProposerServiceClient extends Client {
  /**
   * ProposeBlock drafts exactly block_size tokens conditioned on the
   * committed prefix. Unknown model_id returns NOT_FOUND; malformed
   * arguments (empty prefix, non-positive block_size/num_steps)
   * return INVALID_ARGUMENT.
   */
  proposeBlock(
    request: ProposeBlockRequest,
    callback: (error: ServiceError | null, response: ProposeBlockResponse) => void,
  ): ClientUnaryCall;
  proposeBlock(
    request: ProposeBlockRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ProposeBlockResponse) => void,
  ): ClientUnaryCall;
  proposeBlock(
    request: ProposeBlockRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ProposeBlockResponse) => void,
  ): ClientUnaryCall;
}

export const ProposerServiceClient = makeGenericClientConstructor(
  ProposerServiceService,
  "kakeya.v1.ProposerService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ProposerServiceClient;
  service: typeof ProposerServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
