// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.5
// source: kakeya/v1/runtime.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "kakeya.v1";

export interface CreateSessionRequest {
  /**
   * Optional client-supplied label, recorded for diagnostics. Has no
   * effect on session identity; the server still issues the
   * session_id. Empty string = no label.
   */
  clientLabel: string;
  /**
   * Token ids that, when emitted by the verifier sampler during
   * Generate, cause the server to stop emitting and end the stream
   * with GenerateDone.stop_reason = STOP_REASON_EOS. The runtime
   * does NOT interpret these tokens semantically (ADR 0008 §2.4) —
   * they are opaque ids supplied by the SDK / application based on
   * its own knowledge of the model's tokenizer. Empty list =
   * generation only stops on STOP_REASON_MAX_TOKENS, on
   * STOP_REASON_TRUNCATED, or on cancellation.
   */
  eosTokenIds: number[];
}

export interface CreateSessionResponse {
  /**
   * Server-issued opaque identifier. Treat as a black box; do not
   * attempt to parse, derive new ids from, or reuse across runtime
   * process restarts.
   */
  sessionId: string;
}

export interface AppendTokensRequest {
  /**
   * Target session. Must reference a session previously returned by
   * CreateSession; otherwise returns NOT_FOUND (ADR 0008 §2.6).
   */
  sessionId: string;
  /**
   * Raw token ids to append. Each id must be in the verifier's
   * tokenizer vocabulary range; out-of-range ids return
   * INVALID_ARGUMENT and the session's history is unchanged.
   */
  tokenIds: number[];
}

export interface AppendTokensResponse {
  /**
   * Total number of tokens in the session's history after this
   * append. Useful for SDK-side bookkeeping and history-length
   * assertions.
   */
  historyLength: string;
}

export interface CloseSessionRequest {
  sessionId: string;
}

export interface CloseSessionResponse {
  /**
   * Number of tokens that were in the session's history at close
   * time. Diagnostic only; clients should not depend on this for
   * correctness.
   */
  finalHistoryLength: string;
}

export interface GenerateRequest {
  sessionId: string;
  /**
   * Maximum tokens to emit in this Generate call. Generation may
   * stop earlier if (a) the verifier sampler emits one of the
   * session's eos_token_ids (STOP_REASON_EOS), (b) the session's
   * history would exceed the verifier's sink+window capacity
   * (STOP_REASON_TRUNCATED, default per ADR 0008 §8 OQ-2), or
   * (c) the call is cancelled (STOP_REASON_CANCELLED).
   */
  maxTokens: number;
  /**
   * Deterministic-sampling seed. ADR 0008 §8 OQ-4 default while
   * unresolved: the seed is a per-Generate argument; the byte-exact
   * determinism contract (§2.3) is parameterized over a fixed seed.
   * Field is proto3-optional so the SDK can distinguish "no seed
   * pinned, sampler may use process entropy" from "seed = 0
   * pinned" (both are valid).
   */
  seed?:
    | string
    | undefined;
  /**
   * Sampling parameters, all optional. Documented here for the SDK
   * contract; the runtime passes these through to the verifier
   * sampler without further interpretation in v0.3.
   */
  temperature?: number | undefined;
  topP?: number | undefined;
  topK?: number | undefined;
}

/**
 * GenerateResponse is one frame of the server-streaming response.
 * Exactly one terminal Done event is emitted per Generate call,
 * after which the stream closes cleanly. Despite the "Response"
 * suffix (per proto3 / buf STANDARD convention), each individual
 * instance is conceptually one *event* in the stream — see the
 * `payload` oneof.
 */
export interface GenerateResponse {
  /**
   * A single committed token id, in the order the verifier
   * accepted it.
   */
  tokenId?:
    | number
    | undefined;
  /** Terminal event. Sent exactly once at the end of the stream. */
  done?:
    | GenerateDone
    | undefined;
  /**
   * History was truncated to fit within the verifier's
   * sink+window capacity (ADR 0008 §8 OQ-2 default). Emitted at
   * most once per Generate call, before any token_id event in
   * that call. The truncation discards the oldest non-sink tokens;
   * no information beyond what was discarded is recoverable.
   */
  truncated?: HistoryTruncated | undefined;
}

export interface GenerateDone {
  stopReason: GenerateDone_StopReason;
  /**
   * Number of tokens this Generate call appended to the session
   * history (excludes the prefill phase).
   */
  generatedTokenCount: number;
  /**
   * Wall-clock duration of the prefill phase for this call, in
   * seconds. Exposes the §2.9 metric `generate_prefill_duration_seconds`
   * observation that this call contributed.
   */
  prefillDurationSeconds: number;
  /** Wall-clock duration from prefill start to last token committed. */
  totalDurationSeconds: number;
}

export enum GenerateDone_StopReason {
  UNSPECIFIED = 0,
  MAX_TOKENS = 1,
  EOS = 2,
  CANCELLED = 3,
  TRUNCATED = 4,
  UNRECOGNIZED = -1,
}

export function generateDone_StopReasonFromJSON(object: any): GenerateDone_StopReason {
  switch (object) {
    case 0:
    case "STOP_REASON_UNSPECIFIED":
      return GenerateDone_StopReason.UNSPECIFIED;
    case 1:
    case "STOP_REASON_MAX_TOKENS":
      return GenerateDone_StopReason.MAX_TOKENS;
    case 2:
    case "STOP_REASON_EOS":
      return GenerateDone_StopReason.EOS;
    case 3:
    case "STOP_REASON_CANCELLED":
      return GenerateDone_StopReason.CANCELLED;
    case 4:
    case "STOP_REASON_TRUNCATED":
      return GenerateDone_StopReason.TRUNCATED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GenerateDone_StopReason.UNRECOGNIZED;
  }
}

export function generateDone_StopReasonToJSON(object: GenerateDone_StopReason): string {
  switch (object) {
    case GenerateDone_StopReason.UNSPECIFIED:
      return "STOP_REASON_UNSPECIFIED";
    case GenerateDone_StopReason.MAX_TOKENS:
      return "STOP_REASON_MAX_TOKENS";
    case GenerateDone_StopReason.EOS:
      return "STOP_REASON_EOS";
    case GenerateDone_StopReason.CANCELLED:
      return "STOP_REASON_CANCELLED";
    case GenerateDone_StopReason.TRUNCATED:
      return "STOP_REASON_TRUNCATED";
    case GenerateDone_StopReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface HistoryTruncated {
  /**
   * Number of tokens dropped from the history. The verifier slab
   * now holds (sink + window) tokens at most; this event reports
   * history_length - (sink + window) at the moment of truncation.
   */
  droppedTokenCount: string;
}

export interface GetSessionInfoRequest {
  sessionId: string;
}

export interface GetSessionInfoResponse {
  /**
   * Number of tokens currently in the session's history (after any
   * truncation; the runtime never reports a history longer than the
   * slab can hold).
   */
  historyLength: string;
  /**
   * Live KV bytes held by the session's slab. Sum of all sessions'
   * values equals the §2.9 `session_kv_live_bytes` gauge.
   */
  kvLiveBytes: string;
  /**
   * Anomaly-invariant violation counters per ADR 0008 §2.8. MUST be
   * 0 under healthy operation. Non-zero is a paging-grade signal
   * that the session has been failed and the slab freed; the
   * session_id is no longer usable for AppendTokens / Generate
   * (those return NOT_FOUND or FAILED_PRECONDITION).
   */
  cacheInvariantInv1Violations: string;
  cacheInvariantInv2Violations: string;
  /**
   * Wall-clock seconds since this session's last RPC interaction.
   * The runtime evicts sessions idle longer than its configured
   * session_idle_ttl_s (ADR 0008 §2.6 default 1800s).
   */
  idleSeconds: number;
}

function createBaseCreateSessionRequest(): CreateSessionRequest {
  return { clientLabel: "", eosTokenIds: [] };
}

export const CreateSessionRequest: MessageFns<CreateSessionRequest> = {
  encode(message: CreateSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientLabel !== "") {
      writer.uint32(10).string(message.clientLabel);
    }
    writer.uint32(18).fork();
    for (const v of message.eosTokenIds) {
      writer.uint32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientLabel = reader.string();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.eosTokenIds.push(reader.uint32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.eosTokenIds.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSessionRequest {
    return {
      clientLabel: isSet(object.clientLabel)
        ? globalThis.String(object.clientLabel)
        : isSet(object.client_label)
        ? globalThis.String(object.client_label)
        : "",
      eosTokenIds: globalThis.Array.isArray(object?.eosTokenIds)
        ? object.eosTokenIds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.eos_token_ids)
        ? object.eos_token_ids.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: CreateSessionRequest): unknown {
    const obj: any = {};
    if (message.clientLabel !== "") {
      obj.clientLabel = message.clientLabel;
    }
    if (message.eosTokenIds?.length) {
      obj.eosTokenIds = message.eosTokenIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSessionRequest>, I>>(base?: I): CreateSessionRequest {
    return CreateSessionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSessionRequest>, I>>(object: I): CreateSessionRequest {
    const message = createBaseCreateSessionRequest();
    message.clientLabel = object.clientLabel ?? "";
    message.eosTokenIds = object.eosTokenIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseCreateSessionResponse(): CreateSessionResponse {
  return { sessionId: "" };
}

export const CreateSessionResponse: MessageFns<CreateSessionResponse> = {
  encode(message: CreateSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSessionResponse {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: CreateSessionResponse): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSessionResponse>, I>>(base?: I): CreateSessionResponse {
    return CreateSessionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSessionResponse>, I>>(object: I): CreateSessionResponse {
    const message = createBaseCreateSessionResponse();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseAppendTokensRequest(): AppendTokensRequest {
  return { sessionId: "", tokenIds: [] };
}

export const AppendTokensRequest: MessageFns<AppendTokensRequest> = {
  encode(message: AppendTokensRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    writer.uint32(18).fork();
    for (const v of message.tokenIds) {
      writer.uint32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppendTokensRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppendTokensRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.tokenIds.push(reader.uint32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.tokenIds.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AppendTokensRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      tokenIds: globalThis.Array.isArray(object?.tokenIds)
        ? object.tokenIds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.token_ids)
        ? object.token_ids.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: AppendTokensRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.tokenIds?.length) {
      obj.tokenIds = message.tokenIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AppendTokensRequest>, I>>(base?: I): AppendTokensRequest {
    return AppendTokensRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AppendTokensRequest>, I>>(object: I): AppendTokensRequest {
    const message = createBaseAppendTokensRequest();
    message.sessionId = object.sessionId ?? "";
    message.tokenIds = object.tokenIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseAppendTokensResponse(): AppendTokensResponse {
  return { historyLength: "0" };
}

export const AppendTokensResponse: MessageFns<AppendTokensResponse> = {
  encode(message: AppendTokensResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.historyLength !== "0") {
      writer.uint32(8).uint64(message.historyLength);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppendTokensResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppendTokensResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.historyLength = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AppendTokensResponse {
    return {
      historyLength: isSet(object.historyLength)
        ? globalThis.String(object.historyLength)
        : isSet(object.history_length)
        ? globalThis.String(object.history_length)
        : "0",
    };
  },

  toJSON(message: AppendTokensResponse): unknown {
    const obj: any = {};
    if (message.historyLength !== "0") {
      obj.historyLength = message.historyLength;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AppendTokensResponse>, I>>(base?: I): AppendTokensResponse {
    return AppendTokensResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AppendTokensResponse>, I>>(object: I): AppendTokensResponse {
    const message = createBaseAppendTokensResponse();
    message.historyLength = object.historyLength ?? "0";
    return message;
  },
};

function createBaseCloseSessionRequest(): CloseSessionRequest {
  return { sessionId: "" };
}

export const CloseSessionRequest: MessageFns<CloseSessionRequest> = {
  encode(message: CloseSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CloseSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCloseSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CloseSessionRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: CloseSessionRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CloseSessionRequest>, I>>(base?: I): CloseSessionRequest {
    return CloseSessionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CloseSessionRequest>, I>>(object: I): CloseSessionRequest {
    const message = createBaseCloseSessionRequest();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseCloseSessionResponse(): CloseSessionResponse {
  return { finalHistoryLength: "0" };
}

export const CloseSessionResponse: MessageFns<CloseSessionResponse> = {
  encode(message: CloseSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.finalHistoryLength !== "0") {
      writer.uint32(8).uint64(message.finalHistoryLength);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CloseSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCloseSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.finalHistoryLength = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CloseSessionResponse {
    return {
      finalHistoryLength: isSet(object.finalHistoryLength)
        ? globalThis.String(object.finalHistoryLength)
        : isSet(object.final_history_length)
        ? globalThis.String(object.final_history_length)
        : "0",
    };
  },

  toJSON(message: CloseSessionResponse): unknown {
    const obj: any = {};
    if (message.finalHistoryLength !== "0") {
      obj.finalHistoryLength = message.finalHistoryLength;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CloseSessionResponse>, I>>(base?: I): CloseSessionResponse {
    return CloseSessionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CloseSessionResponse>, I>>(object: I): CloseSessionResponse {
    const message = createBaseCloseSessionResponse();
    message.finalHistoryLength = object.finalHistoryLength ?? "0";
    return message;
  },
};

function createBaseGenerateRequest(): GenerateRequest {
  return { sessionId: "", maxTokens: 0, seed: undefined, temperature: undefined, topP: undefined, topK: undefined };
}

export const GenerateRequest: MessageFns<GenerateRequest> = {
  encode(message: GenerateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.maxTokens !== 0) {
      writer.uint32(16).uint32(message.maxTokens);
    }
    if (message.seed !== undefined) {
      writer.uint32(24).uint64(message.seed);
    }
    if (message.temperature !== undefined) {
      writer.uint32(37).float(message.temperature);
    }
    if (message.topP !== undefined) {
      writer.uint32(45).float(message.topP);
    }
    if (message.topK !== undefined) {
      writer.uint32(48).uint32(message.topK);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.maxTokens = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.seed = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.temperature = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.topP = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.topK = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      maxTokens: isSet(object.maxTokens)
        ? globalThis.Number(object.maxTokens)
        : isSet(object.max_tokens)
        ? globalThis.Number(object.max_tokens)
        : 0,
      seed: isSet(object.seed) ? globalThis.String(object.seed) : undefined,
      temperature: isSet(object.temperature) ? globalThis.Number(object.temperature) : undefined,
      topP: isSet(object.topP)
        ? globalThis.Number(object.topP)
        : isSet(object.top_p)
        ? globalThis.Number(object.top_p)
        : undefined,
      topK: isSet(object.topK)
        ? globalThis.Number(object.topK)
        : isSet(object.top_k)
        ? globalThis.Number(object.top_k)
        : undefined,
    };
  },

  toJSON(message: GenerateRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.maxTokens !== 0) {
      obj.maxTokens = Math.round(message.maxTokens);
    }
    if (message.seed !== undefined) {
      obj.seed = message.seed;
    }
    if (message.temperature !== undefined) {
      obj.temperature = message.temperature;
    }
    if (message.topP !== undefined) {
      obj.topP = message.topP;
    }
    if (message.topK !== undefined) {
      obj.topK = Math.round(message.topK);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateRequest>, I>>(base?: I): GenerateRequest {
    return GenerateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateRequest>, I>>(object: I): GenerateRequest {
    const message = createBaseGenerateRequest();
    message.sessionId = object.sessionId ?? "";
    message.maxTokens = object.maxTokens ?? 0;
    message.seed = object.seed ?? undefined;
    message.temperature = object.temperature ?? undefined;
    message.topP = object.topP ?? undefined;
    message.topK = object.topK ?? undefined;
    return message;
  },
};

function createBaseGenerateResponse(): GenerateResponse {
  return { tokenId: undefined, done: undefined, truncated: undefined };
}

export const GenerateResponse: MessageFns<GenerateResponse> = {
  encode(message: GenerateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tokenId !== undefined) {
      writer.uint32(8).uint32(message.tokenId);
    }
    if (message.done !== undefined) {
      GenerateDone.encode(message.done, writer.uint32(18).fork()).join();
    }
    if (message.truncated !== undefined) {
      HistoryTruncated.encode(message.truncated, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tokenId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.done = GenerateDone.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.truncated = HistoryTruncated.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateResponse {
    return {
      tokenId: isSet(object.tokenId)
        ? globalThis.Number(object.tokenId)
        : isSet(object.token_id)
        ? globalThis.Number(object.token_id)
        : undefined,
      done: isSet(object.done) ? GenerateDone.fromJSON(object.done) : undefined,
      truncated: isSet(object.truncated) ? HistoryTruncated.fromJSON(object.truncated) : undefined,
    };
  },

  toJSON(message: GenerateResponse): unknown {
    const obj: any = {};
    if (message.tokenId !== undefined) {
      obj.tokenId = Math.round(message.tokenId);
    }
    if (message.done !== undefined) {
      obj.done = GenerateDone.toJSON(message.done);
    }
    if (message.truncated !== undefined) {
      obj.truncated = HistoryTruncated.toJSON(message.truncated);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateResponse>, I>>(base?: I): GenerateResponse {
    return GenerateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateResponse>, I>>(object: I): GenerateResponse {
    const message = createBaseGenerateResponse();
    message.tokenId = object.tokenId ?? undefined;
    message.done = (object.done !== undefined && object.done !== null)
      ? GenerateDone.fromPartial(object.done)
      : undefined;
    message.truncated = (object.truncated !== undefined && object.truncated !== null)
      ? HistoryTruncated.fromPartial(object.truncated)
      : undefined;
    return message;
  },
};

function createBaseGenerateDone(): GenerateDone {
  return { stopReason: 0, generatedTokenCount: 0, prefillDurationSeconds: 0, totalDurationSeconds: 0 };
}

export const GenerateDone: MessageFns<GenerateDone> = {
  encode(message: GenerateDone, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stopReason !== 0) {
      writer.uint32(8).int32(message.stopReason);
    }
    if (message.generatedTokenCount !== 0) {
      writer.uint32(16).uint32(message.generatedTokenCount);
    }
    if (message.prefillDurationSeconds !== 0) {
      writer.uint32(25).double(message.prefillDurationSeconds);
    }
    if (message.totalDurationSeconds !== 0) {
      writer.uint32(33).double(message.totalDurationSeconds);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateDone {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateDone();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.stopReason = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.generatedTokenCount = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.prefillDurationSeconds = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.totalDurationSeconds = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateDone {
    return {
      stopReason: isSet(object.stopReason)
        ? generateDone_StopReasonFromJSON(object.stopReason)
        : isSet(object.stop_reason)
        ? generateDone_StopReasonFromJSON(object.stop_reason)
        : 0,
      generatedTokenCount: isSet(object.generatedTokenCount)
        ? globalThis.Number(object.generatedTokenCount)
        : isSet(object.generated_token_count)
        ? globalThis.Number(object.generated_token_count)
        : 0,
      prefillDurationSeconds: isSet(object.prefillDurationSeconds)
        ? globalThis.Number(object.prefillDurationSeconds)
        : isSet(object.prefill_duration_seconds)
        ? globalThis.Number(object.prefill_duration_seconds)
        : 0,
      totalDurationSeconds: isSet(object.totalDurationSeconds)
        ? globalThis.Number(object.totalDurationSeconds)
        : isSet(object.total_duration_seconds)
        ? globalThis.Number(object.total_duration_seconds)
        : 0,
    };
  },

  toJSON(message: GenerateDone): unknown {
    const obj: any = {};
    if (message.stopReason !== 0) {
      obj.stopReason = generateDone_StopReasonToJSON(message.stopReason);
    }
    if (message.generatedTokenCount !== 0) {
      obj.generatedTokenCount = Math.round(message.generatedTokenCount);
    }
    if (message.prefillDurationSeconds !== 0) {
      obj.prefillDurationSeconds = message.prefillDurationSeconds;
    }
    if (message.totalDurationSeconds !== 0) {
      obj.totalDurationSeconds = message.totalDurationSeconds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateDone>, I>>(base?: I): GenerateDone {
    return GenerateDone.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateDone>, I>>(object: I): GenerateDone {
    const message = createBaseGenerateDone();
    message.stopReason = object.stopReason ?? 0;
    message.generatedTokenCount = object.generatedTokenCount ?? 0;
    message.prefillDurationSeconds = object.prefillDurationSeconds ?? 0;
    message.totalDurationSeconds = object.totalDurationSeconds ?? 0;
    return message;
  },
};

function createBaseHistoryTruncated(): HistoryTruncated {
  return { droppedTokenCount: "0" };
}

export const HistoryTruncated: MessageFns<HistoryTruncated> = {
  encode(message: HistoryTruncated, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.droppedTokenCount !== "0") {
      writer.uint32(8).uint64(message.droppedTokenCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoryTruncated {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoryTruncated();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.droppedTokenCount = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoryTruncated {
    return {
      droppedTokenCount: isSet(object.droppedTokenCount)
        ? globalThis.String(object.droppedTokenCount)
        : isSet(object.dropped_token_count)
        ? globalThis.String(object.dropped_token_count)
        : "0",
    };
  },

  toJSON(message: HistoryTruncated): unknown {
    const obj: any = {};
    if (message.droppedTokenCount !== "0") {
      obj.droppedTokenCount = message.droppedTokenCount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HistoryTruncated>, I>>(base?: I): HistoryTruncated {
    return HistoryTruncated.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HistoryTruncated>, I>>(object: I): HistoryTruncated {
    const message = createBaseHistoryTruncated();
    message.droppedTokenCount = object.droppedTokenCount ?? "0";
    return message;
  },
};

function createBaseGetSessionInfoRequest(): GetSessionInfoRequest {
  return { sessionId: "" };
}

export const GetSessionInfoRequest: MessageFns<GetSessionInfoRequest> = {
  encode(message: GetSessionInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSessionInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSessionInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSessionInfoRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: GetSessionInfoRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSessionInfoRequest>, I>>(base?: I): GetSessionInfoRequest {
    return GetSessionInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSessionInfoRequest>, I>>(object: I): GetSessionInfoRequest {
    const message = createBaseGetSessionInfoRequest();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseGetSessionInfoResponse(): GetSessionInfoResponse {
  return {
    historyLength: "0",
    kvLiveBytes: "0",
    cacheInvariantInv1Violations: "0",
    cacheInvariantInv2Violations: "0",
    idleSeconds: 0,
  };
}

export const GetSessionInfoResponse: MessageFns<GetSessionInfoResponse> = {
  encode(message: GetSessionInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.historyLength !== "0") {
      writer.uint32(8).uint64(message.historyLength);
    }
    if (message.kvLiveBytes !== "0") {
      writer.uint32(16).uint64(message.kvLiveBytes);
    }
    if (message.cacheInvariantInv1Violations !== "0") {
      writer.uint32(24).uint64(message.cacheInvariantInv1Violations);
    }
    if (message.cacheInvariantInv2Violations !== "0") {
      writer.uint32(32).uint64(message.cacheInvariantInv2Violations);
    }
    if (message.idleSeconds !== 0) {
      writer.uint32(41).double(message.idleSeconds);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSessionInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSessionInfoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.historyLength = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.kvLiveBytes = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.cacheInvariantInv1Violations = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.cacheInvariantInv2Violations = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.idleSeconds = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSessionInfoResponse {
    return {
      historyLength: isSet(object.historyLength)
        ? globalThis.String(object.historyLength)
        : isSet(object.history_length)
        ? globalThis.String(object.history_length)
        : "0",
      kvLiveBytes: isSet(object.kvLiveBytes)
        ? globalThis.String(object.kvLiveBytes)
        : isSet(object.kv_live_bytes)
        ? globalThis.String(object.kv_live_bytes)
        : "0",
      cacheInvariantInv1Violations: isSet(object.cacheInvariantInv1Violations)
        ? globalThis.String(object.cacheInvariantInv1Violations)
        : isSet(object.cache_invariant_inv1_violations)
        ? globalThis.String(object.cache_invariant_inv1_violations)
        : "0",
      cacheInvariantInv2Violations: isSet(object.cacheInvariantInv2Violations)
        ? globalThis.String(object.cacheInvariantInv2Violations)
        : isSet(object.cache_invariant_inv2_violations)
        ? globalThis.String(object.cache_invariant_inv2_violations)
        : "0",
      idleSeconds: isSet(object.idleSeconds)
        ? globalThis.Number(object.idleSeconds)
        : isSet(object.idle_seconds)
        ? globalThis.Number(object.idle_seconds)
        : 0,
    };
  },

  toJSON(message: GetSessionInfoResponse): unknown {
    const obj: any = {};
    if (message.historyLength !== "0") {
      obj.historyLength = message.historyLength;
    }
    if (message.kvLiveBytes !== "0") {
      obj.kvLiveBytes = message.kvLiveBytes;
    }
    if (message.cacheInvariantInv1Violations !== "0") {
      obj.cacheInvariantInv1Violations = message.cacheInvariantInv1Violations;
    }
    if (message.cacheInvariantInv2Violations !== "0") {
      obj.cacheInvariantInv2Violations = message.cacheInvariantInv2Violations;
    }
    if (message.idleSeconds !== 0) {
      obj.idleSeconds = message.idleSeconds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSessionInfoResponse>, I>>(base?: I): GetSessionInfoResponse {
    return GetSessionInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSessionInfoResponse>, I>>(object: I): GetSessionInfoResponse {
    const message = createBaseGetSessionInfoResponse();
    message.historyLength = object.historyLength ?? "0";
    message.kvLiveBytes = object.kvLiveBytes ?? "0";
    message.cacheInvariantInv1Violations = object.cacheInvariantInv1Violations ?? "0";
    message.cacheInvariantInv2Violations = object.cacheInvariantInv2Violations ?? "0";
    message.idleSeconds = object.idleSeconds ?? 0;
    return message;
  },
};

/**
 * RuntimeService is the single service exposed by a Kakeya runtime
 * instance. All session lifecycle and inference RPCs live here. v0.3
 * is single-tenant; multi-tenant authorization is deferred to v0.4
 * (ADR 0008 §4.5) and is intentionally not modeled in this schema.
 */
export type RuntimeServiceService = typeof RuntimeServiceService;
export const RuntimeServiceService = {
  /**
   * CreateSession allocates a new session and returns its server-
   * issued identifier. Clients cannot fabricate session ids; this RPC
   * is the only way to obtain one (ADR 0008 §2.2 contract item 1).
   */
  createSession: {
    path: "/kakeya.v1.RuntimeService/CreateSession" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateSessionRequest): Buffer => Buffer.from(CreateSessionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateSessionRequest => CreateSessionRequest.decode(value),
    responseSerialize: (value: CreateSessionResponse): Buffer =>
      Buffer.from(CreateSessionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateSessionResponse => CreateSessionResponse.decode(value),
  },
  /**
   * AppendTokens appends raw token ids to a session's history. The
   * history is append-only within a session; clients cannot rewrite
   * prior history mid-session (ADR 0008 §2.2 contract item 3). The
   * server treats token ids as opaque integers and does NOT call any
   * chat template, role marker, or template re-rendering logic
   * (ADR 0008 §2.4).
   */
  appendTokens: {
    path: "/kakeya.v1.RuntimeService/AppendTokens" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AppendTokensRequest): Buffer => Buffer.from(AppendTokensRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AppendTokensRequest => AppendTokensRequest.decode(value),
    responseSerialize: (value: AppendTokensResponse): Buffer =>
      Buffer.from(AppendTokensResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AppendTokensResponse => AppendTokensResponse.decode(value),
  },
  /**
   * Generate requests up to GenerateRequest.max_tokens of generation
   * bound to a session_id. The server streams generated token ids
   * back as they commit (server-streaming RPC). The byte-exact KV
   * cache binding contract (ADR 0008 §2.3) applies: for the same
   * (session_id, history_token_ids, seed) tuple, repeated Generate
   * calls produce bit-identical output regardless of how the history
   * was built up (one AppendTokens of N tokens vs. N AppendTokens of
   * 1 token vs. CreateSession+AppendTokens combinations).
   */
  generate: {
    path: "/kakeya.v1.RuntimeService/Generate" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: GenerateRequest): Buffer => Buffer.from(GenerateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GenerateRequest => GenerateRequest.decode(value),
    responseSerialize: (value: GenerateResponse): Buffer => Buffer.from(GenerateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GenerateResponse => GenerateResponse.decode(value),
  },
  /**
   * CloseSession releases a session and frees its KV slab. Subsequent
   * RPCs that reference the closed session_id return NOT_FOUND.
   */
  closeSession: {
    path: "/kakeya.v1.RuntimeService/CloseSession" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CloseSessionRequest): Buffer => Buffer.from(CloseSessionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CloseSessionRequest => CloseSessionRequest.decode(value),
    responseSerialize: (value: CloseSessionResponse): Buffer =>
      Buffer.from(CloseSessionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CloseSessionResponse => CloseSessionResponse.decode(value),
  },
  /**
   * GetSessionInfo returns diagnostic counters for a session. Used
   * primarily by SDK observability helpers and integration tests
   * (ADR 0008 §2.9). Subset of the metrics also exposed on the
   * Prometheus /metrics endpoint of the deprecated HTTP shim.
   */
  getSessionInfo: {
    path: "/kakeya.v1.RuntimeService/GetSessionInfo" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetSessionInfoRequest): Buffer =>
      Buffer.from(GetSessionInfoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetSessionInfoRequest => GetSessionInfoRequest.decode(value),
    responseSerialize: (value: GetSessionInfoResponse): Buffer =>
      Buffer.from(GetSessionInfoResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetSessionInfoResponse => GetSessionInfoResponse.decode(value),
  },
} as const;

export interface RuntimeServiceServer extends UntypedServiceImplementation {
  /**
   * CreateSession allocates a new session and returns its server-
   * issued identifier. Clients cannot fabricate session ids; this RPC
   * is the only way to obtain one (ADR 0008 §2.2 contract item 1).
   */
  createSession: handleUnaryCall<CreateSessionRequest, CreateSessionResponse>;
  /**
   * AppendTokens appends raw token ids to a session's history. The
   * history is append-only within a session; clients cannot rewrite
   * prior history mid-session (ADR 0008 §2.2 contract item 3). The
   * server treats token ids as opaque integers and does NOT call any
   * chat template, role marker, or template re-rendering logic
   * (ADR 0008 §2.4).
   */
  appendTokens: handleUnaryCall<AppendTokensRequest, AppendTokensResponse>;
  /**
   * Generate requests up to GenerateRequest.max_tokens of generation
   * bound to a session_id. The server streams generated token ids
   * back as they commit (server-streaming RPC). The byte-exact KV
   * cache binding contract (ADR 0008 §2.3) applies: for the same
   * (session_id, history_token_ids, seed) tuple, repeated Generate
   * calls produce bit-identical output regardless of how the history
   * was built up (one AppendTokens of N tokens vs. N AppendTokens of
   * 1 token vs. CreateSession+AppendTokens combinations).
   */
  generate: handleServerStreamingCall<GenerateRequest, GenerateResponse>;
  /**
   * CloseSession releases a session and frees its KV slab. Subsequent
   * RPCs that reference the closed session_id return NOT_FOUND.
   */
  closeSession: handleUnaryCall<CloseSessionRequest, CloseSessionResponse>;
  /**
   * GetSessionInfo returns diagnostic counters for a session. Used
   * primarily by SDK observability helpers and integration tests
   * (ADR 0008 §2.9). Subset of the metrics also exposed on the
   * Prometheus /metrics endpoint of the deprecated HTTP shim.
   */
  getSessionInfo: handleUnaryCall<GetSessionInfoRequest, GetSessionInfoResponse>;
}

export interface RuntimeServiceClient extends Client {
  /**
   * CreateSession allocates a new session and returns its server-
   * issued identifier. Clients cannot fabricate session ids; this RPC
   * is the only way to obtain one (ADR 0008 §2.2 contract item 1).
   */
  createSession(
    request: CreateSessionRequest,
    callback: (error: ServiceError | null, response: CreateSessionResponse) => void,
  ): ClientUnaryCall;
  createSession(
    request: CreateSessionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateSessionResponse) => void,
  ): ClientUnaryCall;
  createSession(
    request: CreateSessionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateSessionResponse) => void,
  ): ClientUnaryCall;
  /**
   * AppendTokens appends raw token ids to a session's history. The
   * history is append-only within a session; clients cannot rewrite
   * prior history mid-session (ADR 0008 §2.2 contract item 3). The
   * server treats token ids as opaque integers and does NOT call any
   * chat template, role marker, or template re-rendering logic
   * (ADR 0008 §2.4).
   */
  appendTokens(
    request: AppendTokensRequest,
    callback: (error: ServiceError | null, response: AppendTokensResponse) => void,
  ): ClientUnaryCall;
  appendTokens(
    request: AppendTokensRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AppendTokensResponse) => void,
  ): ClientUnaryCall;
  appendTokens(
    request: AppendTokensRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AppendTokensResponse) => void,
  ): ClientUnaryCall;
  /**
   * Generate requests up to GenerateRequest.max_tokens of generation
   * bound to a session_id. The server streams generated token ids
   * back as they commit (server-streaming RPC). The byte-exact KV
   * cache binding contract (ADR 0008 §2.3) applies: for the same
   * (session_id, history_token_ids, seed) tuple, repeated Generate
   * calls produce bit-identical output regardless of how the history
   * was built up (one AppendTokens of N tokens vs. N AppendTokens of
   * 1 token vs. CreateSession+AppendTokens combinations).
   */
  generate(request: GenerateRequest, options?: Partial<CallOptions>): ClientReadableStream<GenerateResponse>;
  generate(
    request: GenerateRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<GenerateResponse>;
  /**
   * CloseSession releases a session and frees its KV slab. Subsequent
   * RPCs that reference the closed session_id return NOT_FOUND.
   */
  closeSession(
    request: CloseSessionRequest,
    callback: (error: ServiceError | null, response: CloseSessionResponse) => void,
  ): ClientUnaryCall;
  closeSession(
    request: CloseSessionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CloseSessionResponse) => void,
  ): ClientUnaryCall;
  closeSession(
    request: CloseSessionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CloseSessionResponse) => void,
  ): ClientUnaryCall;
  /**
   * GetSessionInfo returns diagnostic counters for a session. Used
   * primarily by SDK observability helpers and integration tests
   * (ADR 0008 §2.9). Subset of the metrics also exposed on the
   * Prometheus /metrics endpoint of the deprecated HTTP shim.
   */
  getSessionInfo(
    request: GetSessionInfoRequest,
    callback: (error: ServiceError | null, response: GetSessionInfoResponse) => void,
  ): ClientUnaryCall;
  getSessionInfo(
    request: GetSessionInfoRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetSessionInfoResponse) => void,
  ): ClientUnaryCall;
  getSessionInfo(
    request: GetSessionInfoRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetSessionInfoResponse) => void,
  ): ClientUnaryCall;
}

export const RuntimeServiceClient = makeGenericClientConstructor(
  RuntimeServiceService,
  "kakeya.v1.RuntimeService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): RuntimeServiceClient;
  service: typeof RuntimeServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
