from pathlib import Path
import re
import subprocess


ROOT = Path(__file__).resolve().parents[3]
LEAN_SOURCE = ROOT / "KakeyaLeanGate" / "WeilPositivity.lean"
ROUTE_DOC = ROOT / "docs" / "weil-positivity-route.md"


def test_weil_module_has_no_proof_shortcuts():
    source = LEAN_SOURCE.read_text()
    forbidden = ("sorry", "admit", "axiom")
    code = re.sub(r"/-.*?-/", "", source, flags=re.DOTALL)
    code = "\n".join(line.split("--", 1)[0] for line in code.splitlines())
    for token in forbidden:
        assert token not in code


def test_weil_module_compiles_under_pinned_toolchain():
    result = subprocess.run(
        ["lake", "env", "lean", str(LEAN_SOURCE.relative_to(ROOT))],
        cwd=ROOT,
        text=True,
        capture_output=True,
        timeout=120,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_route_document_records_exact_unproved_bridge():
    text = ROUTE_DOC.read_text()
    assert "BridgeObligation W := IsPositive W ↔ RiemannHypothesis" in text
    assert re.search(r"supplies no\s+inhabitant", text, flags=re.IGNORECASE)
    assert "C_c^\\infty((0,\\infty),\\mathbb C)" in text


def test_weil_route_exposes_finite_and_limit_interfaces():
    source = LEAN_SOURCE.read_text()
    required = (
        "MellinNormalizationObligation",
        "zetaZeroWindowFinset",
        "positiveNontrivialZetaZeroWindow_finite",
        "positiveNontrivialZetaZeroWindowFinset",
        "centeredZetaZeroWindowFinset",
        "localCenteredZetaNeighbors",
        "localCenteredZetaNeighbors_nodup",
        "mem_localCenteredZetaNeighbors",
        "zetaZeroMultiplicity",
        "positiveNontrivialZetaZeroCount",
        "positiveNontrivialZetaZeroCount_mono",
        "positiveNontrivialZetaZeroShellCount_le",
        "ActualRiemannVonMangoldtBound",
        "ActualRiemannVonMangoldtBound.shell_count_le",
        "riemannVonMangoldtMain_add_error_le_quadratic",
        "ActualRiemannVonMangoldtBound.shell_count_le_quadratic",
        "vonMangoldt_lseries_eq_neg_logDeriv",
        "vonMangoldtTerm",
        "vonMangoldtPartialSum_tendsto_logDeriv",
        "vonMangoldtPartialSum_add_tail",
        "PrimeSmoothingWeight",
        "smoothedVonMangoldt_summable",
        "smoothedVonMangoldtSeries_tendsto_logDeriv",
        "archimedeanLogDeriv_eq_digamma",
        "archimedeanLogDeriv_one",
        "digamma_nat_add_one",
        "digammaNatError_le_log_succ_sub_log",
        "digammaNatError_tendsto_zero",
        "norm_digamma_nat_add_one_sub_log_le",
        "archimedeanAtTwoStage_eq",
        "finiteCompletedLogDerivAtTwo",
        "archimedeanGammaApproximationAtTwo",
        "ArchimedeanGammaApproximation.tendsto",
        "exponentiallyWeightedTest",
        "stripDerivativeMajorant",
        "hasCompactSupport_iteratedDeriv",
        "integrable_stripDerivativeMajorant",
        "norm_iteratedDeriv_exponentiallyWeightedTest_le",
        "integral_norm_iteratedDeriv_exponentiallyWeightedTest_le",
        "transform_vertical_eq_fourier",
        "norm_transform_vertical_pow_le",
        "stripTransformDecayConstant",
        "transformCLM",
        "transformCLM_apply",
        "spectralShiftTest",
        "transform_spectralShiftTest",
        "normalizedRealBumpTest",
        "normalizedBumpTest",
        "transform_normalizedBumpTest_zero",
        "pointNormalizedTest",
        "transform_pointNormalizedTest_self",
        "pointInterpolationMatrix",
        "simultaneousInterpolatingTest",
        "transform_simultaneousInterpolatingTest",
        "pointInterpolationMatrix_finOne_isUnit",
        "translateTest",
        "transform_translateTest",
        "spectralZeroFactor",
        "transform_spectralZeroFactor",
        "spectralZeroProduct",
        "transform_spectralZeroProduct",
        "localSpectralSeparator",
        "transform_localSpectralSeparator_self",
        "transform_localSpectralSeparator_eq_zero",
        "LocalSeparatorGap",
        "exists_pairLocalSeparatorGap",
        "localPairSeparator",
        "transform_localPairSeparator_target",
        "transform_localPairSeparator_partner",
        "transform_localPairSeparator_nearby_eq_zero",
        "translatedBasisMatrix",
        "translatedBasisMatrix_eq_diagonal_mul_vandermonde",
        "translatedBasisMatrix_det_ne_zero",
        "translatedBasisMatrix_det_ne_zero_iff",
        "translatedBasisMatrix_finTwo_det",
        "translatedBasisMatrix_det_isUnit",
        "translatedInterpolatingTest",
        "translatedInterpolationCoefficients",
        "translatedInterpolationWeight",
        "transform_translatedInterpolatingTest_eq_sum",
        "transform_translatedInterpolatingTest",
        "exists_test_transform_ne_zero_on_finset",
        "exp_eq_exp_of_abs_im_sub_lt_two_pi",
        "collisionFreeTranslationStep",
        "collisionFreeTranslationStep_pos",
        "collisionFreeTranslationStep_nodes_injective",
        "exists_translatedInterpolatingTest",
        "spectralSymmetryClosure",
        "mem_spectralSymmetryClosure",
        "exists_test_transform_ne_zero_on_symmetryClosure",
        "norm_transform_strip_derivative_le",
        "norm_transform_strip_pow_le_explicit",
        "norm_transform_centered_strip_im_pow_le_explicit",
        "norm_transform_translatedInterpolatingTest_strip_pow_le",
        "StripUniformSchwartzSeminormBound",
        "norm_transform_strip_pow_le",
        "zero_stripUniformSchwartzSeminormBound",
        "transform_involution_imaginary",
        "transform_involution",
        "transform_convolution",
        "transform_convolution_involution",
        "norm_transform_convolution_involution_strip_pow_le",
        "transform_localPairSeparator_square_target",
        "transform_localPairSeparator_square_partner",
        "transform_localPairSeparator_square_nearby_eq_zero",
        "norm_transform_localPairSeparator_square_strip_pow_le",
        "norm_transform_translatedInterpolatorSquare_strip_pow_le",
        "nearCollisionSpectralPair",
        "nearCollisionSpectralPair_injective",
        "norm_translatedBasisMatrix_nearCollision_det_le",
        "exists_convolutionSquare_transform_eq",
        "exists_convolutionSquare_negative_on_offCritical_pair",
        "transform_convolution_involution_imaginary",
        "transform_convolution_involution_pureImaginary",
        "finiteZeroSum",
        "finitePrimePowerSum",
        "MultiplicityAwareSymmetricZeros",
        "symmetricZeroPartialSum_tendsto",
        "symmetricZeroFinsetSum",
        "symmetricZeroFinsetSum_re_lt_of_target",
        "symmetricZeroFinsetSum_re_neg_of_target",
        "exists_convolutionSquare_selectedPairTerm_neg",
        "localPairSeparator_selectedPairTerm",
        "localPairSeparator_nearbyPairTerm_eq_zero",
        "symmetricZeroRegularized_reindex",
        "ZeroOrbitNormallyConvergent",
        "residualOrbitNormMass",
        "ZeroOrbitNormallyConvergent.residual_summable",
        "ZeroOrbitNormallyConvergent.norm_sum_erase_le_residual",
        "ZeroOrbitNormallyConvergent.residualOrbitNormMass_le",
        "symmetricZeroRegularized_re_neg_of_tail_domination",
        "symmetricZeroRegularized_re_neg_of_selected_dominates",
        "symmetricZeroRegularized_re_neg_of_selected_dominates_majorant",
        "ZeroOrbitNormallyConvergent.of_bound",
        "ZeroOrbitShells",
        "ZeroOrbitNormallyConvergent.of_shell_count_decay",
        "ZeroOrbitNormallyConvergent.of_shell_mass_decay",
        "ZetaZeroShellCountObligation",
        "ZetaZeroShellCountObligation.representative_re_zero_of_rh",
        "riemannVonMangoldtMain",
        "riemannVonMangoldtError",
        "RiemannVonMangoldtExplicitObligation",
        "RiemannVonMangoldtExplicitObligation.shell_count_le",
        "RiemannVonMangoldtExplicitObligation.normalConvergence",
        "ZetaZeroShellCountObligation.normalConvergence",
        "exists_tsum_nat_add_lt_of_summable",
        "ActualRiemannVonMangoldtBound.exists_envelope_tail_lt",
        "ActualRiemannVonMangoldtBound.shell_weighted_decay_le",
        "ActualRiemannVonMangoldtBound.summable_fourthPower_envelope",
        "ActualRiemannVonMangoldtBound.exists_fourthPower_tail_lt",
        "actualZetaZeroShellWeightedMass",
        "ActualRiemannVonMangoldtBound.exists_actual_shell_tail_lt",
        "actualZetaZeroTransformShellMass",
        "actualZetaZeroTransformShellMass_le",
        "ActualRiemannVonMangoldtBound.exists_actual_transform_tail_lt",
        "ActualRiemannVonMangoldtBound.exists_actual_transform_tail_lt_multiplicity",
        "riemannZeta_eq_zero_iff_completedRiemannZeta_eq_zero_of_strip",
        "riemannZeta_one_sub_eq_zero_of_strip",
        "centeredRiemannZeta_neg_eq_zero",
        "riemannZeta_conj_of_one_lt_re",
        "conjugateReflectedRiemannZeta",
        "riemannZeta_conj",
        "iteratedDeriv_conj_conj",
        "riemannZeta_star_eq_zero_iff",
        "analyticAt_completedRiemannZeta",
        "nontrivialRiemannZetaZeros_countable",
        "ActualNontrivialZetaZero",
        "actualCenteredNontrivialZetaZeros",
        "actualZetaZeroCenteringEquiv",
        "actualCenteredZetaMultiplicity",
        "actualCenteredZetaMultiplicity_centering",
        "zetaZeroMultiplicity_star",
        "completedZetaZeroMultiplicity",
        "zetaZeroMultiplicity_eq_completed",
        "completedZetaZeroMultiplicity_one_sub",
        "zetaZeroMultiplicity_one_sub",
        "completedRiemannZeta_star_eq_zero_iff",
        "completedZetaZeroMultiplicity_star",
        "riemannXi",
        "differentiable_riemannXi",
        "analyticOnNhd_riemannXi",
        "riemannXi_one_sub",
        "riemannXi_eq_mul_completedRiemannZeta",
        "riemannXi_eq_zero_iff_riemannZeta_eq_zero_of_strip",
        "riemannXiZeroMultiplicity",
        "riemannXiZeroMultiplicity_eq_zeta",
        "analytic_logDeriv_local_normalForm",
        "riemannXi_two_ne_zero",
        "riemannXi_analyticOrderAt_ne_top",
        "riemannXi_logDeriv_local_normalForm",
        "riemannXi_logDeriv_local",
        "XiPunctureData",
        "exists_riemannXiPunctureData",
        "riemannXiPunctureData",
        "XiPunctureData.on_sphere",
        "XiPunctureData.circleIntegral_logDeriv_eq",
        "riemannXi_finset_sum_puncture_integrals",
        "XiPunctureData.circleIntegral_mul_logDeriv_eq",
        "riemannXi_finset_sum_puncture_integrals_mul",
        "riemannXi_circleAverage_log_norm_eq_divisor_sum",
        "riemannXi_sum_divisor_le",
        "riemannXi_divisor_apply",
        "riemannXi_finset_divisor_sum_eq_multiplicity",
        "actualCenteredNontrivialZetaZeros_neg_star",
        "actualCenteredZetaMultiplicity_neg_star",
        "actualPositiveCenteredZetaZeros",
        "ActualPositiveCenteredZetaZero",
        "actualPositiveCenteredZetaZeros_countable",
        "actualPositiveCenteredPartner",
        "actualPositiveCenteredPartner_fixed_iff",
        "actualPositiveCenteredPartner_ne_iff",
        "actualPositiveCenteredOrbitSetoid",
        "ActualZetaZeroOrbit",
        "actualZetaZeroOrbit_mk_eq_iff",
        "actualZetaZeroOrbitDecode",
        "actualZetaZeroOrbitCode",
        "actualZetaZeroOrbitDecode_complete",
        "actualZetaZeroOrbitDecode_injective",
        "actualZetaZeroOrbitMultiplicity",
        "actualPositiveCenteredZeroWindow",
        "actualPositiveCenteredZeroWindow_finite",
        "actualZetaZeroOrbitWindow",
        "actualZetaZeroOrbitWindow_finite",
        "actualZetaZeroOrbit_complete",
        "ExactActualZetaOrbitModel",
        "ExactActualZetaOrbitModel.isZetaZero",
        "ExactActualZetaOrbitModel.partner_mem",
        "ExactActualZetaOrbitModel.partner_multiplicity_eq",
        "ExactActualZetaOrbitModel.partnerIsZetaZero",
        "NontrivialZetaZerosInCriticalStrip",
        "nontrivialZetaZerosInCriticalStrip",
        "ExactActualZetaOrbitModel.riemannHypothesis_of_representatives",
        "ExactActualZetaOrbitModel.riemannHypothesis",
        "riemannHypothesis_of_exactActualOrbits_explicitFormula_and_rvmEnvelope",
        "riemannHypothesis_of_exactActualOrbits_formula_rvm",
        "ZetaZeroShellCountObligation.shell_norm_sum_le",
        "ZetaZeroShellCountObligation.exists_envelope_tail_lt",
        "ZetaZeroShellCountObligation.residualOrbitNormMass_le",
        "ZetaZeroShellCountObligation.residualOrbitNormMass_le_excluding",
        "ZetaZeroShellCountObligation.symmetricZeroRegularized_re_neg",
        "ZetaZeroShellCountObligation.symmetricZeroRegularized_re_neg_excluding",
        "ZetaZeroShellCountObligation.localPairSeparator_regularized_re_neg",
        "ZetaZeroShellCountObligation.localPairSeparator_contradicts_formula",
        "summable_quadratic_shell_fourth_power_decay",
        "ZetaZeroShellCountObligation.normalConvergence_of_fourthPower",
        "SymmetricZeroWindows",
        "symmetricZeroWindowSum_tendsto",
        "symmetricZeroWindowSum_tendsto_of_zetaShellCount",
        "symmetricZeroWindows_difference_tendsto_zero",
        "RestrictedExplicitFormulaData.explicitFormula",
        "RestrictedGuinandWeilLimitData.explicitFormula",
        "RestrictedGuinandWeilShellData.explicitFormula",
        "RestrictedGuinandWeilShellData.explicitFormula_re_nonneg",
        "RestrictedGuinandWeilShellData.explicitFormula_re_nonneg_of_re_zero",
        "RestrictedGuinandWeilShellData.explicitFormula_re_nonneg_of_rh",
        "FiniteFormulaData.IsExactAt",
        "FiniteFormulaData.arithmeticSide_re_neg_of_exact",
        "finiteZeroSum_convolution_eq_energy",
        "finiteZeroSum_convolution_eq_energy_exact",
        "finiteZeroSum_convolution_nonneg_exact",
        "symmetricZeroRegularized_convolution_nonneg",
        "symmetricZeroRegularized_convolution_nonneg_of_re_zero",
        "explicitFormula_passes_to_limit",
        "positivity_passes_to_pointwise_limit",
        "positivity_passes_to_eventual_pointwise_limit",
        "positivity_passes_to_uniform_limit_on",
        "nonnegative_on_closure",
        "nonnegative_of_dense",
        "dense_nonnegative_counterexample_without_continuity",
        "Distribution.evalContinuous_iff_supported",
        "ContinuousDistribution.toDistribution_evalContinuous",
        "ConvolutionSquareContinuous",
        "InvolutionContinuous",
        "ConvolutionContinuous",
        "supportedInvolutionLM",
        "reflectedCompact",
        "supportedReflectionPrecompLM",
        "supportedReflectionSeminormBound",
        "supportedReflectionPrecompCLM",
        "supportedInvolutionCLM",
        "SupportedInvolutionContinuous",
        "supportedInvolutionContinuous",
        "involutionContinuous_of_supported",
        "involutionContinuous",
        "SupportedConvolutionContinuous",
        "convolutionLeftLM",
        "convolutionLeftCLM",
        "convolution_separatelyContinuous_left",
        "convolution_comm",
        "iteratedDeriv_convolution_right",
        "integral_norm_supported_le_measure_mul_seminorm",
        "norm_iteratedDeriv_supported_convolution_le",
        "convolutionCompact",
        "supportedConvolution",
        "supportedConvolution_seminorm_le",
        "supportedIn_isVonNBounded_iff_seminorm_bounded",
        "supportedConvolution_uniform_left_of_isVonNBounded",
        "supportedConvolution_uniform_right_of_isVonNBounded",
        "TestFunction.IsStageVonNBounded",
        "TestFunction.IsStageVonNBounded.isVonNBounded",
        "TestFunction.isStageVonNBounded_singleton",
        "convolutionSet",
        "TestFunction.IsStageVonNBounded.convolutionSet",
        "convolutionSquare_isStageVonNBounded",
        "localPairSeparatorSquare_isStageVonNBounded",
        "TestFunction.StrictLFBoundedRegularity",
        "TestFunction.strictLFBoundedRegularity_iff",
        "convolutionSet_isVonNBounded_of_strictLF",
        "convolutionCompact_mono",
        "supportedConvolution_mono",
        "convolution_sub_sub",
        "supportedConvolution_sub_sub",
        "supportedConvolution_continuous",
        "supportedConvolutionContinuous",
        "convolution_separatelyContinuous_left_unconditional",
        "convolution_separatelyContinuous_right_unconditional",
        "TestFunction.stagePairInclusion",
        "TestFunction.continuous_stagePairInclusion",
        "TestFunction.LFPairFinalTopology",
        "TestFunction.lfPairFinalTopology_le_product",
        "TestFunction.LFPairProductTopologyObligation",
        "TestFunction.lfPairProductTopologyObligation_iff",
        "TestFunction.LFPairProductNeighborhoodCriterion",
        "TestFunction.lfPairProductTopologyObligation_iff_neighborhoods",
        "TestFunction.continuous_lfPairFinal",
        "TestFunction.continuous_of_lfPairProductTopology",
        "convolutionContinuous_lfPairFinal",
        "convolutionContinuous_of_lfPairProductTopology",
        "convolution_separatelyContinuous_right",
        "convolutionBilinearLM",
        "TestFunction.LFBilinearProductUniversalProperty",
        "TestFunction.lfBilinearProductUniversalProperty_of_topology",
        "convolutionContinuous_of_lfBilinearProduct",
        "TestFunction.LFProductUniversalProperty",
        "convolutionContinuous_of_lfProduct",
        "convolutionSquareContinuous_of_components",
        "convolutionSquareContinuous_of_convolution",
        "convolutionSquareContinuous_of_lfPairProductTopology",
        "ZeroOrbitConvolutionSquarePositive",
        "ConvolutionSquaresSeparateOffCriticalOrbits",
        "ConvolutionSquaresSeparatePositiveOffCriticalOrbits",
        "RVMEnvelopeSeparatesPositiveOffCriticalOrbits",
        "ZetaZeroShellCountObligation.convolutionSquaresSeparate",
        "representative_re_zero_of_convolutionSquarePositive",
        "representative_re_zero_of_positiveMultiplicity_separation",
        "representative_re_zero_of_explicitFormula_and_rvmEnvelope",
        "zeroMultiplicityOffCriticalModel",
        "pointNormalization_without_positiveMultiplicity_counterexample",
        "Distribution.quadraticContinuous_of_eval_of_convolutionSquare",
        "Distribution.IsPositive.of_dense",
        "positivity_of_error_bound",
        "monotoneQuadratic_limit_nonneg",
        "SymmetricZeroApproximants",
        "PrimePowerApproximants",
        "ArchimedeanApproximants",
        "TypedExplicitApproximants.explicitFormula",
        "ZeroRegularizationObligation",
        "PrimePowerStabilizationObligation",
        "ArchimedeanLimitObligation",
        "AllTestPositivityObligation",
    )
    for declaration in required:
        assert declaration in source


def test_route_document_does_not_claim_full_formula_or_convergence():
    text = ROUTE_DOC.read_text()
    assert "full explicit formula or RH" in text
    assert "explicit hypothesis" in text
    assert "finite-stage nonnegativity alone says nothing" in text
    assert "six named obligations" in text
