# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import distributed_pb2 as kakeya_dot_v1_dot_distributed__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kakeya/v1/distributed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CapabilityServiceStub:
    """-----------------------------------------------------------------------------
    Services
    -----------------------------------------------------------------------------

    CapabilityService is served by every Kakeya node that participates
    in a fleet. Both RPCs are safe to call from any peer at any time;
    neither mutates anything beyond the callee's capability registry.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExchangeCapabilities = channel.unary_unary(
                '/kakeya.v1.CapabilityService/ExchangeCapabilities',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetNodeCapability = channel.unary_unary(
                '/kakeya.v1.CapabilityService/GetNodeCapability',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityResponse.FromString,
                _registered_method=True)


class CapabilityServiceServicer:
    """-----------------------------------------------------------------------------
    Services
    -----------------------------------------------------------------------------

    CapabilityService is served by every Kakeya node that participates
    in a fleet. Both RPCs are safe to call from any peer at any time;
    neither mutates anything beyond the callee's capability registry.
    """

    def ExchangeCapabilities(self, request, context):
        """ExchangeCapabilities is the gossip primitive. The caller sends
        every capability card it currently holds (its own card included);
        the callee merges those cards into its registry (last-writer-wins
        on announced_at_unix, own card never overwritten) and replies
        with its merged view. The caller merges the response. After one
        round both sides hold the union of their prior views.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeCapability(self, request, context):
        """GetNodeCapability returns only the callee's own card. Cheap
        probe used for liveness checks and diagnostics; does not mutate
        the callee's registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExchangeCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeCapabilities,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesResponse.SerializeToString,
            ),
            'GetNodeCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeCapability,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kakeya.v1.CapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kakeya.v1.CapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityService:
    """-----------------------------------------------------------------------------
    Services
    -----------------------------------------------------------------------------

    CapabilityService is served by every Kakeya node that participates
    in a fleet. Both RPCs are safe to call from any peer at any time;
    neither mutates anything beyond the callee's capability registry.
    """

    @staticmethod
    def ExchangeCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.CapabilityService/ExchangeCapabilities',
            kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.CapabilityService/GetNodeCapability',
            kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProposerServiceStub:
    """ProposerService serves speculative-decoding draft blocks. The
    contract is DLMProposer.propose_block (ADR 0001) lifted onto the
    wire: committed prefix in, exactly block_size draft token ids out.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProposeBlock = channel.unary_unary(
                '/kakeya.v1.ProposerService/ProposeBlock',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.ProposeBlockRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.ProposeBlockResponse.FromString,
                _registered_method=True)


class ProposerServiceServicer:
    """ProposerService serves speculative-decoding draft blocks. The
    contract is DLMProposer.propose_block (ADR 0001) lifted onto the
    wire: committed prefix in, exactly block_size draft token ids out.
    """

    def ProposeBlock(self, request, context):
        """ProposeBlock drafts exactly block_size tokens conditioned on the
        committed prefix. Unknown model_id returns NOT_FOUND; malformed
        arguments (empty prefix, non-positive block_size/num_steps)
        return INVALID_ARGUMENT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProposerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProposeBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeBlock,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.ProposeBlockRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.ProposeBlockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kakeya.v1.ProposerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kakeya.v1.ProposerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProposerService:
    """ProposerService serves speculative-decoding draft blocks. The
    contract is DLMProposer.propose_block (ADR 0001) lifted onto the
    wire: committed prefix in, exactly block_size draft token ids out.
    """

    @staticmethod
    def ProposeBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.ProposerService/ProposeBlock',
            kakeya_dot_v1_dot_distributed__pb2.ProposeBlockRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.ProposeBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
