# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import distributed_pb2 as kakeya_dot_v1_dot_distributed__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kakeya/v1/distributed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CapabilityServiceStub:
    """-----------------------------------------------------------------------------
    Services
    -----------------------------------------------------------------------------

    CapabilityService is served by every Kakeya node that participates
    in a fleet. Both RPCs are safe to call from any peer at any time;
    neither mutates anything beyond the callee's capability registry.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExchangeCapabilities = channel.unary_unary(
                '/kakeya.v1.CapabilityService/ExchangeCapabilities',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetNodeCapability = channel.unary_unary(
                '/kakeya.v1.CapabilityService/GetNodeCapability',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityResponse.FromString,
                _registered_method=True)


class CapabilityServiceServicer:
    """-----------------------------------------------------------------------------
    Services
    -----------------------------------------------------------------------------

    CapabilityService is served by every Kakeya node that participates
    in a fleet. Both RPCs are safe to call from any peer at any time;
    neither mutates anything beyond the callee's capability registry.
    """

    def ExchangeCapabilities(self, request, context):
        """ExchangeCapabilities is the gossip primitive. The caller sends
        every capability card it currently holds (its own card included);
        the callee merges those cards into its registry (last-writer-wins
        on announced_at_unix, own card never overwritten) and replies
        with its merged view. The caller merges the response. After one
        round both sides hold the union of their prior views.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeCapability(self, request, context):
        """GetNodeCapability returns only the callee's own card. Cheap
        probe used for liveness checks and diagnostics; does not mutate
        the callee's registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExchangeCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeCapabilities,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesResponse.SerializeToString,
            ),
            'GetNodeCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeCapability,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kakeya.v1.CapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kakeya.v1.CapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityService:
    """-----------------------------------------------------------------------------
    Services
    -----------------------------------------------------------------------------

    CapabilityService is served by every Kakeya node that participates
    in a fleet. Both RPCs are safe to call from any peer at any time;
    neither mutates anything beyond the callee's capability registry.
    """

    @staticmethod
    def ExchangeCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.CapabilityService/ExchangeCapabilities',
            kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.ExchangeCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.CapabilityService/GetNodeCapability',
            kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.GetNodeCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProposerServiceStub:
    """ProposerService serves speculative-decoding draft blocks. The
    contract is DLMProposer.propose_block (ADR 0001) lifted onto the
    wire: committed prefix in, exactly block_size draft token ids out.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProposeBlock = channel.unary_unary(
                '/kakeya.v1.ProposerService/ProposeBlock',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.ProposeBlockRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.ProposeBlockResponse.FromString,
                _registered_method=True)


class ProposerServiceServicer:
    """ProposerService serves speculative-decoding draft blocks. The
    contract is DLMProposer.propose_block (ADR 0001) lifted onto the
    wire: committed prefix in, exactly block_size draft token ids out.
    """

    def ProposeBlock(self, request, context):
        """ProposeBlock drafts exactly block_size tokens conditioned on the
        committed prefix. Unknown model_id returns NOT_FOUND; malformed
        arguments (empty prefix, non-positive block_size/num_steps)
        return INVALID_ARGUMENT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProposerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProposeBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeBlock,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.ProposeBlockRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.ProposeBlockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kakeya.v1.ProposerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kakeya.v1.ProposerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProposerService:
    """ProposerService serves speculative-decoding draft blocks. The
    contract is DLMProposer.propose_block (ADR 0001) lifted onto the
    wire: committed prefix in, exactly block_size draft token ids out.
    """

    @staticmethod
    def ProposeBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.ProposerService/ProposeBlock',
            kakeya_dot_v1_dot_distributed__pb2.ProposeBlockRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.ProposeBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PrefillCacheServiceStub:
    """PrefillCacheService exposes immutable, content-addressed prefill K/V blocks.
    Lookup is metadata-only; FetchBlocks is the point-to-point bulk data plane.
    Decode never calls this service: a requester imports a hit once, computes the
    missing suffix locally, and keeps the autoregressive loop local.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCacheSummary = channel.unary_unary(
                '/kakeya.v1.PrefillCacheService/GetCacheSummary',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.GetCacheSummaryRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.GetCacheSummaryResponse.FromString,
                _registered_method=True)
        self.LookupPrefix = channel.unary_unary(
                '/kakeya.v1.PrefillCacheService/LookupPrefix',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.LookupPrefixRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.LookupPrefixResponse.FromString,
                _registered_method=True)
        self.FetchBlocks = channel.unary_stream(
                '/kakeya.v1.PrefillCacheService/FetchBlocks',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.FetchBlocksRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.FetchBlocksResponse.FromString,
                _registered_method=True)
        self.PublishBlock = channel.stream_unary(
                '/kakeya.v1.PrefillCacheService/PublishBlock',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.PublishBlockRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.PublishBlockResponse.FromString,
                _registered_method=True)


class PrefillCacheServiceServicer:
    """PrefillCacheService exposes immutable, content-addressed prefill K/V blocks.
    Lookup is metadata-only; FetchBlocks is the point-to-point bulk data plane.
    Decode never calls this service: a requester imports a hit once, computes the
    missing suffix locally, and keeps the autoregressive loop local.
    """

    def GetCacheSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupPrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishBlock(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrefillCacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCacheSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheSummary,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.GetCacheSummaryRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.GetCacheSummaryResponse.SerializeToString,
            ),
            'LookupPrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupPrefix,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.LookupPrefixRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.LookupPrefixResponse.SerializeToString,
            ),
            'FetchBlocks': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchBlocks,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.FetchBlocksRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.FetchBlocksResponse.SerializeToString,
            ),
            'PublishBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishBlock,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.PublishBlockRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.PublishBlockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kakeya.v1.PrefillCacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kakeya.v1.PrefillCacheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrefillCacheService:
    """PrefillCacheService exposes immutable, content-addressed prefill K/V blocks.
    Lookup is metadata-only; FetchBlocks is the point-to-point bulk data plane.
    Decode never calls this service: a requester imports a hit once, computes the
    missing suffix locally, and keeps the autoregressive loop local.
    """

    @staticmethod
    def GetCacheSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.PrefillCacheService/GetCacheSummary',
            kakeya_dot_v1_dot_distributed__pb2.GetCacheSummaryRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.GetCacheSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupPrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.PrefillCacheService/LookupPrefix',
            kakeya_dot_v1_dot_distributed__pb2.LookupPrefixRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.LookupPrefixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kakeya.v1.PrefillCacheService/FetchBlocks',
            kakeya_dot_v1_dot_distributed__pb2.FetchBlocksRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.FetchBlocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kakeya.v1.PrefillCacheService/PublishBlock',
            kakeya_dot_v1_dot_distributed__pb2.PublishBlockRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.PublishBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PrefillWorkerServiceStub:
    """PrefillWorkerService executes model prefill only. Workers load the same model
    as the primary, materialize immutable snapshots into their co-located
    PrefillCacheService, and never participate in autoregressive decode.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitPrefillJob = channel.unary_unary(
                '/kakeya.v1.PrefillWorkerService/SubmitPrefillJob',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.SubmitPrefillJobRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.SubmitPrefillJobResponse.FromString,
                _registered_method=True)
        self.GetPrefillJobStatus = channel.unary_unary(
                '/kakeya.v1.PrefillWorkerService/GetPrefillJobStatus',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.GetPrefillJobStatusRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.GetPrefillJobStatusResponse.FromString,
                _registered_method=True)
        self.CancelPrefillJob = channel.unary_unary(
                '/kakeya.v1.PrefillWorkerService/CancelPrefillJob',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.CancelPrefillJobRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.CancelPrefillJobResponse.FromString,
                _registered_method=True)


class PrefillWorkerServiceServicer:
    """PrefillWorkerService executes model prefill only. Workers load the same model
    as the primary, materialize immutable snapshots into their co-located
    PrefillCacheService, and never participate in autoregressive decode.
    """

    def SubmitPrefillJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrefillJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPrefillJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrefillWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitPrefillJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPrefillJob,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.SubmitPrefillJobRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.SubmitPrefillJobResponse.SerializeToString,
            ),
            'GetPrefillJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrefillJobStatus,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.GetPrefillJobStatusRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.GetPrefillJobStatusResponse.SerializeToString,
            ),
            'CancelPrefillJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelPrefillJob,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.CancelPrefillJobRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.CancelPrefillJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kakeya.v1.PrefillWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kakeya.v1.PrefillWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrefillWorkerService:
    """PrefillWorkerService executes model prefill only. Workers load the same model
    as the primary, materialize immutable snapshots into their co-located
    PrefillCacheService, and never participate in autoregressive decode.
    """

    @staticmethod
    def SubmitPrefillJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.PrefillWorkerService/SubmitPrefillJob',
            kakeya_dot_v1_dot_distributed__pb2.SubmitPrefillJobRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.SubmitPrefillJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrefillJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.PrefillWorkerService/GetPrefillJobStatus',
            kakeya_dot_v1_dot_distributed__pb2.GetPrefillJobStatusRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.GetPrefillJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelPrefillJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.PrefillWorkerService/CancelPrefillJob',
            kakeya_dot_v1_dot_distributed__pb2.CancelPrefillJobRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.CancelPrefillJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DFlashProposerServiceStub:
    """DFlashProposerService: stateful remote DFlash drafter + f_θ restoration.
    Per turn: Restore (prompt -> f_θ-projected verifier K/V) then SeedContext
    (verifier aux hidden -> drafter context K/V). Per decode block: DraftBlock
    (bonus + context_len -> draft tokens) then ExtendContext (committed aux ->
    grow drafter context). CloseSession frees host-B state.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Restore = channel.unary_unary(
                '/kakeya.v1.DFlashProposerService/Restore',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.RestoreRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.RestoreResponse.FromString,
                _registered_method=True)
        self.SeedContext = channel.unary_unary(
                '/kakeya.v1.DFlashProposerService/SeedContext',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.SeedContextRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.SeedContextResponse.FromString,
                _registered_method=True)
        self.DraftBlock = channel.unary_unary(
                '/kakeya.v1.DFlashProposerService/DraftBlock',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.DraftBlockRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.DraftBlockResponse.FromString,
                _registered_method=True)
        self.ExtendContext = channel.unary_unary(
                '/kakeya.v1.DFlashProposerService/ExtendContext',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.ExtendContextRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.ExtendContextResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/kakeya.v1.DFlashProposerService/CloseSession',
                request_serializer=kakeya_dot_v1_dot_distributed__pb2.DFlashProposerServiceCloseSessionRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_distributed__pb2.DFlashProposerServiceCloseSessionResponse.FromString,
                _registered_method=True)


class DFlashProposerServiceServicer:
    """DFlashProposerService: stateful remote DFlash drafter + f_θ restoration.
    Per turn: Restore (prompt -> f_θ-projected verifier K/V) then SeedContext
    (verifier aux hidden -> drafter context K/V). Per decode block: DraftBlock
    (bonus + context_len -> draft tokens) then ExtendContext (committed aux ->
    grow drafter context). CloseSession frees host-B state.
    """

    def Restore(self, request, context):
        """Restore drafts the f_θ-projected verifier K/V banks for the prompt: host B
        embeds prompt_ids (verifier embedding), runs the DFlash drafter, and maps
        its K/V through f_θ into verifier K/V space. With s5_exact_full_attn the
        full-attention layers are omitted (the verifier's native cache owns them);
        only sliding-layer banks are returned. Opens the session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeedContext(self, request, context):
        """SeedContext builds host B's drafter context K/V from the verifier's aux
        hidden states over the prompt (host A computed these during its prefill).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DraftBlock(self, request, context):
        """DraftBlock returns exactly block_size draft tokens for the upcoming block,
        conditioned on the verifier's bonus token + the session's context K/V.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtendContext(self, request, context):
        """ExtendContext appends the aux hidden of the just-committed tokens to host
        B's drafter context K/V (O(block_size), not O(prefix)).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """CloseSession releases host-B per-session state. Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DFlashProposerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.RestoreRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.RestoreResponse.SerializeToString,
            ),
            'SeedContext': grpc.unary_unary_rpc_method_handler(
                    servicer.SeedContext,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.SeedContextRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.SeedContextResponse.SerializeToString,
            ),
            'DraftBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DraftBlock,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.DraftBlockRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.DraftBlockResponse.SerializeToString,
            ),
            'ExtendContext': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtendContext,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.ExtendContextRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.ExtendContextResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=kakeya_dot_v1_dot_distributed__pb2.DFlashProposerServiceCloseSessionRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_distributed__pb2.DFlashProposerServiceCloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kakeya.v1.DFlashProposerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kakeya.v1.DFlashProposerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DFlashProposerService:
    """DFlashProposerService: stateful remote DFlash drafter + f_θ restoration.
    Per turn: Restore (prompt -> f_θ-projected verifier K/V) then SeedContext
    (verifier aux hidden -> drafter context K/V). Per decode block: DraftBlock
    (bonus + context_len -> draft tokens) then ExtendContext (committed aux ->
    grow drafter context). CloseSession frees host-B state.
    """

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.DFlashProposerService/Restore',
            kakeya_dot_v1_dot_distributed__pb2.RestoreRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.RestoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeedContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.DFlashProposerService/SeedContext',
            kakeya_dot_v1_dot_distributed__pb2.SeedContextRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.SeedContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DraftBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.DFlashProposerService/DraftBlock',
            kakeya_dot_v1_dot_distributed__pb2.DraftBlockRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.DraftBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtendContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.DFlashProposerService/ExtendContext',
            kakeya_dot_v1_dot_distributed__pb2.ExtendContextRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.ExtendContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.DFlashProposerService/CloseSession',
            kakeya_dot_v1_dot_distributed__pb2.DFlashProposerServiceCloseSessionRequest.SerializeToString,
            kakeya_dot_v1_dot_distributed__pb2.DFlashProposerServiceCloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
