# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runtime_pb2 as kakeya_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kakeya/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub:
    """-----------------------------------------------------------------------------
    Service
    -----------------------------------------------------------------------------

    RuntimeService is the single service exposed by a Kakeya runtime
    instance. All session lifecycle and inference RPCs live here. v0.3
    is single-tenant; multi-tenant authorization is deferred to v0.4
    (ADR 0008 §4.5) and is intentionally not modeled in this schema.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/kakeya.v1.RuntimeService/CreateSession',
                request_serializer=kakeya_dot_v1_dot_runtime__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_runtime__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.AppendTokens = channel.unary_unary(
                '/kakeya.v1.RuntimeService/AppendTokens',
                request_serializer=kakeya_dot_v1_dot_runtime__pb2.AppendTokensRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_runtime__pb2.AppendTokensResponse.FromString,
                _registered_method=True)
        self.Generate = channel.unary_stream(
                '/kakeya.v1.RuntimeService/Generate',
                request_serializer=kakeya_dot_v1_dot_runtime__pb2.GenerateRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_runtime__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/kakeya.v1.RuntimeService/CloseSession',
                request_serializer=kakeya_dot_v1_dot_runtime__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_runtime__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionInfo = channel.unary_unary(
                '/kakeya.v1.RuntimeService/GetSessionInfo',
                request_serializer=kakeya_dot_v1_dot_runtime__pb2.GetSessionInfoRequest.SerializeToString,
                response_deserializer=kakeya_dot_v1_dot_runtime__pb2.GetSessionInfoResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer:
    """-----------------------------------------------------------------------------
    Service
    -----------------------------------------------------------------------------

    RuntimeService is the single service exposed by a Kakeya runtime
    instance. All session lifecycle and inference RPCs live here. v0.3
    is single-tenant; multi-tenant authorization is deferred to v0.4
    (ADR 0008 §4.5) and is intentionally not modeled in this schema.
    """

    def CreateSession(self, request, context):
        """CreateSession allocates a new session and returns its server-
        issued identifier. Clients cannot fabricate session ids; this RPC
        is the only way to obtain one (ADR 0008 §2.2 contract item 1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendTokens(self, request, context):
        """AppendTokens appends raw token ids to a session's history. The
        history is append-only within a session; clients cannot rewrite
        prior history mid-session (ADR 0008 §2.2 contract item 3). The
        server treats token ids as opaque integers and does NOT call any
        chat template, role marker, or template re-rendering logic
        (ADR 0008 §2.4).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Generate requests up to GenerateRequest.max_tokens of generation
        bound to a session_id. The server streams generated token ids
        back as they commit (server-streaming RPC). The byte-exact KV
        cache binding contract (ADR 0008 §2.3) applies: for the same
        (session_id, history_token_ids, seed) tuple, repeated Generate
        calls produce bit-identical output regardless of how the history
        was built up (one AppendTokens of N tokens vs. N AppendTokens of
        1 token vs. CreateSession+AppendTokens combinations).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """CloseSession releases a session and frees its KV slab. Subsequent
        RPCs that reference the closed session_id return NOT_FOUND.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionInfo(self, request, context):
        """GetSessionInfo returns diagnostic counters for a session. Used
        primarily by SDK observability helpers and integration tests
        (ADR 0008 §2.9). Subset of the metrics also exposed on the
        Prometheus /metrics endpoint of the deprecated HTTP shim.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=kakeya_dot_v1_dot_runtime__pb2.CreateSessionRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_runtime__pb2.CreateSessionResponse.SerializeToString,
            ),
            'AppendTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendTokens,
                    request_deserializer=kakeya_dot_v1_dot_runtime__pb2.AppendTokensRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_runtime__pb2.AppendTokensResponse.SerializeToString,
            ),
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=kakeya_dot_v1_dot_runtime__pb2.GenerateRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_runtime__pb2.GenerateResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=kakeya_dot_v1_dot_runtime__pb2.CloseSessionRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_runtime__pb2.CloseSessionResponse.SerializeToString,
            ),
            'GetSessionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionInfo,
                    request_deserializer=kakeya_dot_v1_dot_runtime__pb2.GetSessionInfoRequest.FromString,
                    response_serializer=kakeya_dot_v1_dot_runtime__pb2.GetSessionInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kakeya.v1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kakeya.v1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService:
    """-----------------------------------------------------------------------------
    Service
    -----------------------------------------------------------------------------

    RuntimeService is the single service exposed by a Kakeya runtime
    instance. All session lifecycle and inference RPCs live here. v0.3
    is single-tenant; multi-tenant authorization is deferred to v0.4
    (ADR 0008 §4.5) and is intentionally not modeled in this schema.
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.RuntimeService/CreateSession',
            kakeya_dot_v1_dot_runtime__pb2.CreateSessionRequest.SerializeToString,
            kakeya_dot_v1_dot_runtime__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.RuntimeService/AppendTokens',
            kakeya_dot_v1_dot_runtime__pb2.AppendTokensRequest.SerializeToString,
            kakeya_dot_v1_dot_runtime__pb2.AppendTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kakeya.v1.RuntimeService/Generate',
            kakeya_dot_v1_dot_runtime__pb2.GenerateRequest.SerializeToString,
            kakeya_dot_v1_dot_runtime__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.RuntimeService/CloseSession',
            kakeya_dot_v1_dot_runtime__pb2.CloseSessionRequest.SerializeToString,
            kakeya_dot_v1_dot_runtime__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kakeya.v1.RuntimeService/GetSessionInfo',
            kakeya_dot_v1_dot_runtime__pb2.GetSessionInfoRequest.SerializeToString,
            kakeya_dot_v1_dot_runtime__pb2.GetSessionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
