#!/usr/bin/env python3
"""Real Karpathy-style AutoResearch supervisor around one-shot GAN experiments."""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import plistlib
import re
import shutil
import socket
import subprocess
import threading
import time
import urllib.request
from pathlib import Path

from autoresearch.prefill.prepare import _load_candidate, evaluate


REQUIRED_CANDIDATE_FIELDS = (
    "candidate_id",
    "target_obligation_id",
    "hypothesis",
    "generator_directive",
    "critic_directive",
    "prefill_compute_chunk_tokens",
)


def _json_request(url: str) -> dict:
    with urllib.request.urlopen(url, timeout=10) as response:
        return json.load(response)


def _wait_port(host: str, port: int, timeout_s: float = 180) -> None:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        try:
            with socket.create_connection((host, port), timeout=2):
                return
        except OSError:
            time.sleep(2)
    raise TimeoutError(f"service did not become ready: {host}:{port}")


def _candidate_snapshot(module) -> dict:
    return {
        "candidate_id": str(module.CANDIDATE_ID),
        "target_obligation_id": str(module.TARGET_OBLIGATION_ID),
        "hypothesis": str(module.HYPOTHESIS),
        "generator_directive": str(module.GENERATOR_DIRECTIVE),
        "critic_directive": str(module.CRITIC_DIRECTIVE),
        "prefill_compute_chunk_tokens": int(
            module.PREFILL_COMPUTE_CHUNK_TOKENS,
        ),
        "snapshot_mode": str(module.SNAPSHOT_MODE),
        "max_segment_seconds": float(module.MAX_SEGMENT_SECONDS),
        "require_full_context": bool(module.REQUIRE_FULL_CONTEXT),
        "allow_fallback": bool(module.ALLOW_FALLBACK),
    }


def validate_candidate(candidate: dict) -> None:
    missing = [field for field in REQUIRED_CANDIDATE_FIELDS if not candidate.get(field)]
    if missing:
        raise ValueError(f"candidate missing fields: {missing}")
    if candidate["prefill_compute_chunk_tokens"] not in (64, 128, 256):
        raise ValueError("chunk tokens must be one of 64, 128, 256")
    if candidate.get("snapshot_mode", "final_only") != "final_only":
        raise ValueError("snapshot mode must remain final_only")
    if candidate.get("require_full_context", True) is not True:
        raise ValueError("candidate must require full context")
    if candidate.get("allow_fallback", False) is not False:
        raise ValueError("candidate must forbid fallback")


def render_candidate(candidate: dict) -> str:
    validate_candidate(candidate)
    return (
        '"""AutoResearch agent-editable strategy. Generated by supervisor."""\n\n'
        f"CANDIDATE_ID = {candidate['candidate_id']!r}\n"
        f"TARGET_OBLIGATION_ID = {candidate['target_obligation_id']!r}\n"
        f"HYPOTHESIS = {candidate['hypothesis']!r}\n"
        f"GENERATOR_DIRECTIVE = {candidate['generator_directive']!r}\n"
        f"CRITIC_DIRECTIVE = {candidate['critic_directive']!r}\n"
        f"PREFILL_COMPUTE_CHUNK_TOKENS = "
        f"{candidate['prefill_compute_chunk_tokens']}\n"
        'SNAPSHOT_MODE = "final_only"\n'
        f"MAX_SEGMENT_SECONDS = {candidate.get('max_segment_seconds', 300.0)!r}\n"
        "REQUIRE_FULL_CONTEXT = True\n"
        "ALLOW_FALLBACK = False\n"
    )


def _extract_json(text: str) -> dict:
    stripped = text.strip()
    if stripped.startswith("```"):
        stripped = re.sub(r"^```(?:json)?\\s*", "", stripped)
        stripped = re.sub(r"\\s*```$", "", stripped)
    start, end = stripped.find("{"), stripped.rfind("}")
    if start < 0 or end <= start:
        raise ValueError("strategy agent returned no JSON object")
    return json.loads(stripped[start:end + 1])


def propose_candidate(
    *,
    address: str,
    tokenizer_id: str,
    program: str,
    current: dict,
    results_text: str,
    ledger: dict,
) -> dict:
    from kakeya import Client
    from transformers import AutoTokenizer
    from scripts.chat_grpc import _resolve_eos_token_ids

    tokenizer = AutoTokenizer.from_pretrained(tokenizer_id)
    prompt = (
        "You are the AutoResearch strategy agent. Follow the human-owned "
        "program exactly. Select one unresolved proof obligation and propose "
        "one falsifiable GAN strategy experiment. Return JSON only with keys: "
        + ", ".join(REQUIRED_CANDIDATE_FIELDS)
        + ". Allowed prefill_compute_chunk_tokens: 64, 128, 256. "
        "Do not weaken full context, final-only snapshots, or no-fallback rules."
        f"\n\nPROGRAM:\n{program}\n\nCURRENT:\n{json.dumps(current)}"
        f"\n\nRESULTS:\n{results_text[-12000:]}"
        f"\n\nLEDGER:\n{json.dumps(ledger)}"
    )
    ids = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        add_generation_prompt=True,
        tokenize=True,
        return_dict=False,
        enable_thinking=False,
    )
    generated: list[int] = []
    with Client(address) as client:
        with client.create_session(
            eos_token_ids=_resolve_eos_token_ids(tokenizer),
            client_label="autoresearch-strategy",
        ) as session:
            session.append(ids)
            while len(generated) < 2048:
                before = len(generated)
                generated.extend(int(token) for token in session.generate(max_tokens=64))
                if session.last_stop_reason != 1:
                    break
                if len(generated) == before:
                    raise RuntimeError("strategy agent made no progress")
            if session.last_stop_reason != 2:
                raise RuntimeError(
                    f"strategy agent did not reach EOS: {session.last_stop_reason}",
                )
    candidate = _extract_json(
        tokenizer.decode(generated, skip_special_tokens=True),
    )
    candidate.update({
        "snapshot_mode": "final_only",
        "max_segment_seconds": 300.0,
        "require_full_context": True,
        "allow_fallback": False,
    })
    validate_candidate(candidate)
    return candidate


def deploy_candidate(worker_ssh: str, chunk_tokens: int) -> None:
    remote = f"""python3 - <<'PY'
import os, plistlib
from pathlib import Path
p=Path.home()/'Library/LaunchAgents/ai.kakeya.prefill-worker.plist'
d=plistlib.loads(p.read_bytes())
a=d['ProgramArguments']
i=a.index('--prefill-compute-chunk-tokens')
a[i+1]='{chunk_tokens}'
t=p.with_suffix('.plist.tmp')
t.write_bytes(plistlib.dumps(d))
os.chmod(t,0o644)
t.replace(p)
PY
launchctl bootout gui/$(id -u)/ai.kakeya.prefill-worker 2>/dev/null || true
sleep 3
launchctl bootstrap gui/$(id -u) \"$HOME/Library/LaunchAgents/ai.kakeya.prefill-worker.plist\"
launchctl kickstart -k gui/$(id -u)/ai.kakeya.prefill-worker
"""
    subprocess.run(
        ["ssh", "-o", "BatchMode=yes", worker_ssh, remote],
        check=True,
    )
    _wait_port("169.254.27.104", 53051)
    probe = subprocess.run(
        ["ssh", worker_ssh, "ps -ax -o command="],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    expected = f"--prefill-compute-chunk-tokens {chunk_tokens}"
    if expected not in probe:
        raise RuntimeError("deployed worker chunk size verification failed")


def clear_primary_cache() -> None:
    subprocess.run(
        [
            "launchctl", "kickstart", "-k",
            f"gui/{os.getuid()}/ai.kakeya.grpc-runtime-prefill",
        ],
        check=True,
    )
    _wait_port("127.0.0.1", 51051)
    _wait_port("127.0.0.1", 8090)


def _backup(path: Path) -> bytes | None:
    return path.read_bytes() if path.exists() else None


def _restore(path: Path, content: bytes | None) -> None:
    if content is None:
        path.unlink(missing_ok=True)
    else:
        temporary = path.with_suffix(path.suffix + ".restore")
        temporary.write_bytes(content)
        os.chmod(temporary, 0o600)
        temporary.replace(path)


def run_gan_experiment(
    *,
    repo: Path,
    candidate_path: Path,
    state_path: Path,
    timeout_s: float,
) -> tuple[str, dict, str]:
    command = [
        "bash", str(repo / "scripts/run_agent_gan_repl.sh"),
        "--skip-ensure", "--no-auto-loop",
        "--candidate-file", str(candidate_path),
        "--state-file", str(state_path),
    ]
    process = subprocess.Popen(
        command,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        cwd=repo,
    )
    assert process.stdin is not None
    assert process.stdout is not None
    process.stdin.write("/continue\n/quit\n")
    process.stdin.flush()
    process.stdin.close()
    timed_out = threading.Event()

    def terminate_on_timeout() -> None:
        timed_out.set()
        process.kill()

    timer = threading.Timer(timeout_s, terminate_on_timeout)
    timer.daemon = True
    timer.start()
    lines: list[str] = []
    try:
        for line in process.stdout:
            print(line, end="", flush=True)
            lines.append(line)
        returncode = process.wait()
    finally:
        timer.cancel()
    output = "".join(lines)
    if timed_out.is_set():
        raise TimeoutError(
            f"GAN experiment exceeded {timeout_s}s: {output[-4000:]}",
        )
    if returncode != 0:
        raise RuntimeError(
            f"GAN experiment failed ({returncode}): {output[-4000:]}",
        )
    matches = re.findall(r"run=(br_[0-9a-f]+)", output)
    if not matches:
        raise RuntimeError("GAN experiment produced no benchmark run id")
    run_id = matches[-1]
    report = _json_request(
        f"http://127.0.0.1:8090/v1/network/benchmarks/{run_id}",
    )
    if report.get("status") != "completed":
        raise RuntimeError(f"GAN benchmark is not completed: {report.get('status')}")
    return run_id, report, output


def read_results(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def best_kept(results: list[dict]) -> dict | None:
    kept = [row for row in results if row.get("kept") == "True"]
    if not kept:
        return None
    return min(
        kept,
        key=lambda row: (
            int(row["proof_obligations_unresolved"]),
            float(row["metric_cold_critic_prefill_s"]),
        ),
    )


def should_keep(result: dict, baseline: dict | None) -> bool:
    if not result["accepted"]:
        return False
    if baseline is None:
        return True
    new_key = (
        int(result["proof_obligations_unresolved"]),
        float(result["metric_cold_critic_prefill_s"]),
    )
    old_key = (
        int(baseline["proof_obligations_unresolved"]),
        float(baseline["metric_cold_critic_prefill_s"]),
    )
    return new_key < old_key


RESULT_FIELDS = (
    "timestamp", "experiment_id", "run_id", "candidate_id",
    "target_obligation_id", "constraints_pass", "accepted", "kept",
    "metric_cold_critic_prefill_s", "baseline_metric_s",
    "proof_obligations_total", "proof_obligations_covered",
    "proof_obligations_unresolved", "compute_chunk_tokens",
    "candidate_sha256", "report_path",
)


def append_result(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    write_header = not path.exists()
    with path.open("a", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=RESULT_FIELDS, delimiter="\t")
        if write_header:
            writer.writeheader()
        writer.writerow({field: row.get(field, "") for field in RESULT_FIELDS})


def run_iteration(args, iteration: int) -> dict:
    root = Path(__file__).resolve().parents[2]
    ar = Path(__file__).resolve().parent
    candidate_path = ar / "candidate.py"
    results_path = Path(args.results).expanduser()
    reports_dir = Path(args.reports_dir).expanduser()
    reports_dir.mkdir(parents=True, exist_ok=True)
    state_path = Path(args.state_file).expanduser()
    ledger_path = Path(args.proof_ledger).expanduser()
    program = (ar / "program.md").read_text()
    results = read_results(results_path)
    baseline = best_kept(results)
    current_module = _load_candidate(candidate_path)
    current = _candidate_snapshot(current_module)
    previous_candidate = candidate_path.read_bytes()
    previous_state = _backup(state_path)
    previous_ledger = _backup(ledger_path)
    previous_chunk = int(current["prefill_compute_chunk_tokens"])

    proposed = current
    try:
        print(
            f"[autoresearch] iteration={iteration} "
            f"phase=predeploy-current candidate={current['candidate_id']}",
            flush=True,
        )
        deploy_candidate(args.worker_ssh, previous_chunk)
        clear_primary_cache()
        if baseline is None and iteration == 0:
            print(
                "[autoresearch] phase=baseline using current candidate",
                flush=True,
            )
        else:
            print(
                "[autoresearch] phase=strategy-proposal real-gemma",
                flush=True,
            )
            proposed = propose_candidate(
                address=args.address,
                tokenizer_id=args.tokenizer_id,
                program=program,
                current=current,
                results_text=(
                    results_path.read_text() if results_path.exists() else ""
                ),
                ledger=json.loads(ledger_path.read_text()),
            )
            candidate_path.write_text(render_candidate(proposed))
            print(
                f"[autoresearch] phase=candidate-written "
                f"candidate={proposed['candidate_id']} "
                f"target={proposed['target_obligation_id']}",
                flush=True,
            )
            deploy_candidate(
                args.worker_ssh,
                proposed["prefill_compute_chunk_tokens"],
            )
            clear_primary_cache()
        validate_candidate(proposed)
        experiment_id = (
            f"ar_{int(time.time())}_{iteration}_"
            f"{hashlib.sha256(candidate_path.read_bytes()).hexdigest()[:8]}"
        )
        report_path = reports_dir / f"{experiment_id}.json"
        print(
            f"[autoresearch] phase=gan-experiment id={experiment_id}",
            flush=True,
        )
        run_id, report, _ = run_gan_experiment(
            repo=root,
            candidate_path=candidate_path,
            state_path=state_path,
            timeout_s=args.experiment_timeout_s,
        )
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2))
        candidate_module = _load_candidate(candidate_path)
        result = evaluate(report, candidate_module)
        keep = should_keep(result, baseline)
        print(
            f"[autoresearch] phase=evaluate accepted={result['accepted']} "
            f"unresolved={result['proof_obligations_unresolved']} "
            f"prefill_s={result['metric_cold_critic_prefill_s']:.3f} "
            f"decision={'keep' if keep else 'revert'}",
            flush=True,
        )
        row = {
            "timestamp": time.time(),
            "experiment_id": experiment_id,
            "run_id": run_id,
            "candidate_id": proposed["candidate_id"],
            "target_obligation_id": proposed["target_obligation_id"],
            "constraints_pass": result["accepted"],
            "accepted": result["accepted"],
            "kept": keep,
            "metric_cold_critic_prefill_s": result[
                "metric_cold_critic_prefill_s"
            ],
            "baseline_metric_s": (
                baseline["metric_cold_critic_prefill_s"] if baseline else ""
            ),
            "proof_obligations_total": result["proof_obligations_total"],
            "proof_obligations_covered": result["proof_obligations_covered"],
            "proof_obligations_unresolved": result[
                "proof_obligations_unresolved"
            ],
            "compute_chunk_tokens": result["compute_chunk_tokens"],
            "candidate_sha256": hashlib.sha256(
                candidate_path.read_bytes(),
            ).hexdigest(),
            "report_path": str(report_path),
        }
        append_result(results_path, row)
        if not keep:
            candidate_path.write_bytes(previous_candidate)
            _restore(state_path, previous_state)
            _restore(ledger_path, previous_ledger)
            deploy_candidate(args.worker_ssh, previous_chunk)
            print("[autoresearch] phase=reverted", flush=True)
        else:
            print("[autoresearch] phase=kept", flush=True)
        return row
    except Exception as exc:
        print(
            f"[autoresearch] phase=failed error={type(exc).__name__}: {exc}",
            flush=True,
        )
        candidate_path.write_bytes(previous_candidate)
        _restore(state_path, previous_state)
        _restore(ledger_path, previous_ledger)
        deploy_candidate(args.worker_ssh, previous_chunk)
        raise


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--iterations", type=int, default=1)
    parser.add_argument("--worker-ssh", default="allens")
    parser.add_argument("--address", default="127.0.0.1:51051")
    parser.add_argument(
        "--tokenizer-id",
        default=str(
            Path.home()
            / "kakeya-models/gemma-4-26B-A4B-it-mlx-4bit"
        ),
    )
    parser.add_argument(
        "--results",
        default=str(Path.home() / ".kakeya/autoresearch/prefill/results.tsv"),
    )
    parser.add_argument(
        "--reports-dir",
        default=str(Path.home() / ".kakeya/autoresearch/prefill/reports"),
    )
    parser.add_argument(
        "--state-file",
        default=str(Path.home() / ".kakeya/agent_gan_state.json"),
    )
    parser.add_argument(
        "--proof-ledger",
        default=str(Path.home() / ".kakeya/agent_gan_proof_ledger.json"),
    )
    parser.add_argument("--experiment-timeout-s", type=float, default=7200)
    args = parser.parse_args()
    if args.iterations <= 0:
        raise SystemExit("iterations must be > 0")
    for iteration in range(args.iterations):
        row = run_iteration(args, iteration)
        print(json.dumps(row, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
